cmd/thv/app/run.go, go.mod, go.sum
This ensures folks have fresh images, since the latest truly should mean
latest
=> Always pull the latest reference if using `latest` tag

README.md
The following PR adds installation instructions for toolhive.
=> Update the README with installation instructions

.goreleaser.yaml, cmd/thv/app/commands.go, cmd/thv/app/common.go, cmd/thv/app/config.go, cmd/thv/app/list.go, cmd/thv/app/logs.go, cmd/thv/app/proxy.go, cmd/thv/app/registry.go, cmd/thv/app/restart.go, cmd/thv/app/rm.go, cmd/thv/app/run.go, cmd/thv/app/run_common.go, cmd/thv/app/search.go, cmd/thv/app/secret.go, cmd/thv/app/stop.go, cmd/thv/app/version.go, cmd/thv/main.go
* should fix the version command output
* renames the cli package to app (matching the folder name)
Closes https://github.com/StacklokLabs/toolhive/issues/153
=> Fix the version command output while releasing

cmd/thv/app/search.go
We had the same issue as with the registry list which was already
solved. Let's solve it here too.
=> Use actual name entry in search

pkg/registry/data/registry.json
This was migrated to the official mcp namespce in docker
=> Update Firecrawl packaging

.github/workflows/image-build-and-publish.yml, .github/workflows/verify-docgen.yml
=> Use go version from `go.mod` and latest `ko`

cmd/thv/app/config.go
When registering a new client in ToolHive, it now automatically gets
configured with the currently running MCP servers. This eliminates the
need to stop and re-run MCP servers after registering a new client.
Changes:
- Modified the register-client command to add currently running MCPs to
the newly registered client
- Enhanced the auto-discovery command to update all registered clients
with currently running MCPs when auto-discovery is enabled
- Added a new function to find running MCP servers and update client
configurations
Fixes #109
=> feat: Add current MCPs to newly registered clients

pkg/container/templates/npx.tmpl, pkg/container/templates/templates_test.go
- Switch to Alpine-based Node.js image for smaller size
- Add git for package installation support
- Create non-root user with proper permissions
- Configure npm for faster installations in containers
- Disable unnecessary npm features (funding, audits, notifications)
=> container: optimize NPX template for security and performance

pkg/container/templates/templates_test.go, pkg/container/templates/uvx.tmpl
- Switch to Alpine-based Python image for smaller size
- Create non-root user with proper permissions
- Configure Python environment variables for better container performance
- Optimize pip and uv settings for faster package installations
- Improve Dockerfile structure with clear comments
=> container: optimize UVX template for security and performance

pkg/environment/environment_test.go
This commit adds comprehensive unit tests for the environment package.
=> Add unit tests for environment package

SECURITY.MD
=> docs: update SECURITY.MD

.github/workflows/update-registry.yml, cmd/regup/app/root.go, cmd/regup/app/update.go, cmd/regup/main.go, pkg/registry/data/registry.json
This is meant to update the registry json file.
This also adds a workflow to update this every hour or at will.
=> Add `regup` a small registry updating utility

pkg/runner/config.go
This ensures that we only try to create valid containers.
=> fix: Ignore duplicate volume mount declarations

pkg/registry/data/registry.json
MKP is a kubernetes MCP server ( https://github.com/StacklokLabs/mkp )
=> Add MKP as a packaged kubernetes MCP server

cmd/thv/app/run.go
At the moment, toolhive will pull images if they are tagged as latest and if they don't exist locally. However, because locally built images tend to have "latest" as a tag, toolhive was trying to pull them from `docker.io`. This resulted in a failure because that image was a locally built image.
This PR fixes that logic so that there is a conditional flow of when we pull from remote and when we use local. This allows us to avoid mandating users to use `localhost/` prefixes to their local images.
The logic is the following:
- If ImageTag is `latest` -> pull image
- if error -> check if image exists locally
- if yes: use image
- if no: error saying image doesn't exist either remotely or locally
- if no error -> return image
- If ImageTag is not `latest` -> check if exist locally
- if not -> …
=> fix: sorts out conflicting code between local and remote image pulls

cmd/thv/app/run.go
The following PR should mask the input when being asked for missing env vars and/or secrets. Note that we already do that when a user decided to explicitly add a secret to the secret store.
I wasn't sure if we should fail straight away or move forward to the next variable if reading the input fails (I refer to the `continue` statement in the error check). I chose to move forward but now that I think about it perhaps it's better to fail fast.
Fixes: https://github.com/StacklokLabs/toolhive/issues/307
=> Mask input when being asked for missing env vars/secrets

dco.md
Initial  Developer Certificate of Origin (DCO)
=> Create  Developer Certificate of Origin (DCO)

docs/kind/deploying-mcp-server-with-operator.md, docs/kind/deploying-toolhive-operator.md
Enhancements to deployment documentation
=> Enhancements to deployment documentation

README.md
The following PR updates the flowchart to reflect the architecture better:
* Each MCP server is a separate container
* The proxies do not run as part of the container
**How it renders:**
=> Update the flowchart in README

pkg/container/docker/client.go
This PR adds support for the Docker Desktop socket path on macOS. Docker Desktop on Mac uses a different socket path (`~/.docker/run/docker.sock`) than the standard Linux path (`/var/run/docker.sock`).
Changes made:
1. Added a new constant `DockerDesktopMacSocketPath` to represent the Docker Desktop socket path on macOS
2. Modified the `findContainerSocket` function to check for this additional socket path when looking for Docker sockets
The code now tries the standard Docker socket path first, and if that fails, it also checks the Docker Desktop socket path on macOS. This ensures compatibility with both standard Docker installations and Docker Desktop on macOS.
Fixes #353
=> fix: Add support for Docker Desktop socket path on macOS

pkg/api/server.go, pkg/api/v1/servers.go, pkg/api/v1/version.go, pkg/lifecycle/manager.go
Implement API endpoints for everything except run and restart.
These do not have documentation yet, an OpenAPI spec is being worked on (along with documentation updates).
=> Endpoints for list, get, delete, stop.

.github/workflows/lint-helm-charts.yml, .github/workflows/releaser-helm-charts.yml, .github/workflows/run-on-main-charts.yml, deploy/charts/operator-crds/Chart.yaml, deploy/charts/operator-crds/README.md, deploy/charts/operator/Chart.yaml, deploy/charts/operator/README.md, deploy/charts/operator/ci/autoScalingEnabled-values.yaml, deploy/charts/operator/ci/extraEnvVars-values.yaml, deploy/charts/operator/ci/extraPodAndContainerSecurityContext-values.yaml, deploy/charts/operator/ci/extraPodAnnotationsAndLabels-values.yaml, deploy/charts/operator/ci/extraVolumes-values.yaml
- adds more tests for the operator helm chart
- adds releaser step for the helm charts that publishes charts to ghcr and signs them
Ref: https://github.com/stacklok/toolhive/issues/314
=> feat: adds publish step for operator helm charts

cr.yaml
Ref: https://github.com/stacklok/toolhive/issues/314
=> fix: adds path for charts for releaser

cmd/thv/app/run.go
This PR enhances the security logging for provenance verification by:
1. Changing the log level from `Info` to `Warn` for missing provenance information
2. Adding visual indicators (emojis) to make the verification status more immediately apparent:
- ✅ Success - When verification passes
- ⚠️ Warning - When provenance information is missing
- ❌ Error - When verification fails
These changes improve the user experience by making it easier to quickly identify the status of provenance verification through visual cues, and properly categorize missing provenance information as a warning rather than just informational.
Verified that the log messages display correctly with the appropriate emoji indicators for each verification scenario.
=> Improve security logging for provenance verification with visual indicators

pkg/lifecycle/manager.go
=> Stop running container before removing

cmd/thv/app/run.go, pkg/registry/data/registry.json, pkg/registry/registry_test.go, pkg/registry/types.go
This PR adds comprehensive secret management support for environment variables in the ToolHive MCP server registry system. It introduces a new \`Secret\` field to classify sensitive environment variables and integrates with the existing secret management infrastructure.
Previously, the registry system treated all environment variables equally, with no distinction between sensitive credentials (API keys, passwords, tokens) and regular configuration values. This created security concerns when handling sensitive data.
- **Added Secret field to EnvVar struct**: New boolean field in [\`pkg/registry/types.go\`](https://github.com/stacklok/toolhive/blob/feat/secret-environment-variables/pkg/registry/types.go) to mark environment variables containing sensitive information
- **Updated registry …
=> feat(registry): add secret management support for environment variables

cmd/thv/app/proxy.go
The transparent proxy needs only the base URL and the situation is confusing if we allow paths.
=> Prevent proxying URL with path

pkg/api/v1/registry.go
The following PR adds initial implementation of the Registry API handlers.
=> Initial implementation of the Registry API handlers

pkg/auth/jwt.go, pkg/auth/jwt_test.go
This PR improves the OIDC discovery HTTP client configuration and fixes the well-known endpoint URL to be RFC 8414 compliant.
- **Fix OIDC well-known endpoint URL**: Changed from `openid_configuration` to `openid-configuration` to comply with RFC 8414 standard
- **Add User-Agent header**: Include ToolHive version information for better request identification and debugging
- **Add Accept header**: Explicitly request `application/json` response format
- **Improve HTTP client timeouts**: Enhanced timeout configuration for better reliability:
- TLS handshake timeout: 10 seconds
- Response header timeout: 10 seconds
- Overall request timeout: 30 seconds (unchanged)
- Import `pkg/versions` package to access version information for User-Agent header
- Use proper HTTP transport configuration with …
=> Improve OIDC HTTP client configuration and fix endpoint URL

pkg/workloads/models.go
This is not used yet, but I'm commiting it to allow review.
=> Define Workload API model

README.md
The following PR adds the winget install option to README
=> Add the winget install option to README

pkg/audit/auditor.go, pkg/audit/auditor_test.go, pkg/audit/config.go, pkg/audit/config_test.go, pkg/audit/event.go, pkg/audit/event_test.go, pkg/runner/runner.go
This PR adds a custom audit level to the logging system in the `pkg/audit` package, providing dedicated structured audit logging capabilities.
- **Custom Audit Level**: Added `LevelAudit = slog.Level(2)` - a custom log level between Info and Warn specifically for audit events
- **Native slog Integration**: Implemented `LogTo()` method on `AuditEvent` struct for native slog integration with proper structured attributes
- **Configurable Output**: Added `LogFile` configuration option to write audit logs to specific files or stdout
- **Dedicated Logger**: Created `NewAuditLogger()` function that returns a structured JSON logger always configured for audit logging
- **Error Handling**: Updated `NewAuditor()` to return an error for proper error handling when log files cannot be opened
- …
=> feat: add custom audit level for structured audit logging

.github/workflows/operator-ci.yml, cmd/thv-operator/Taskfile.yml, docs/operator/crd-api.md, docs/operator/crd-ref-config.yaml
=> feat: generate documentation for k8s operator

pkg/secrets/factory.go
Enforces the usage of the OS Keyring when using the `encrypted` provider for secrets
=> Force OS keyring for encrypted provider

pkg/registry/data/registry.json
=> Add the Playwright MCP server to the registry

pkg/registry/data/registry.json
=> Add the Notion MCP server to the registry

pkg/registry/data/registry.json
- ~~Switch to SSE transport~~ (reverted, will revisit once we have port randomization worked out)
- Use upstream image
- Add new env var and refresh tools
=> Update the Atlassian MCP in the registry

pkg/container/docker/client.go
=> fix: do not pass network mode in host, as we rely on network

cmd/thv/app/client.go, cmd/thv/app/config.go
Remove duplicate code and use the client manager whenever registering a new client.
Fix #841
=> Use client manager in CLI client registration

pkg/container/docker/client.go
The fixed the issue where clients were showing 0 tools due to corrupted json.
Ref https://github.com/stacklok/toolhive/issues/846
When the stream wasn't properly demultiplexed, the json was getting corrupted with timestamps in the middle of it.
For example, the `inputSchema` below:
```
{"annotations":{"title":"Manage repository notification subscription","readOnlyHint":false},"description":"Manage a repository notification subscription: ignore, watch, or delete repository notifications subscription for the provided repository.","inputSchema2025-07-04T13:44:23.241360714Z ":{"properties":{"action":{"description":"Action to perform: ignore, watch, or delete the repository notification subscription.","enum":["ignore","watch","delete"],"type":"string"},"owner":{"description":"The account owner …
```
=> Demultiplex stdio container streams

pkg/client/config.go, pkg/client/config_test.go, pkg/runner/runner.go, pkg/workloads/manager.go
=> Only update the config for registered clients

pkg/container/docker/client.go
When ToolHive starts or restarts a workload, it checks to see if a container with the same name exists. If the configuration has changed, it needs to remove the container and recreate it. This happens in a method named `handleExistingContainer`.
Previously, the code used the `RemoveWorkload` method to clean up the old container. However, when the logic to create a separate external Docker network was added, the `RemoveWorkload` method was extended to remove the external network if no workloads were left. If no other workloads are running during a start or restart *and* the run/restart involves a workload with the same name as an exited container in Docker - a situation arises where ToolHive checks to see if the external network exists, then checks to see if there is an existing container, …
=> Fix bug where the external network is killed during run/restart

pkg/runner/config.go, pkg/runner/config_builder.go, pkg/runner/config_test.go
=> Introduce builder for RunConfig

pkg/api/server.go
This adds a middleware to all API calls that checks for updates the same way the CLI functions. For now the throttling mechanism is shared.
=> Add an API middleware to check for updates on API calls

pkg/environment/environment.go
=> fix: propagate mcp vars also for streamable http

cmd/thv/app/run.go, pkg/runner/config.go, pkg/workloads/manager.go
For the moment, add validation of secrets
Closes: #704
=> feat: validate workloads before actually running them

pkg/registry/data/registry.json
The following PR updates the MCP server descriptions. We had comments that most begin with a common "This MCP server is about ..." and we should update them.
=> Update MCP server descriptions

pkg/registry/data/registry.json
The following PR adds the kyverno-mcp server to our registry.
=> Add Kyverno to the MCP registry

.claude/settings.json, .gitignore, CLAUDE.md
This seems like something we should share across the team.
=> Add CLAUDE.md and claude settings file

cmd/thv-operator/controllers/mcpserver_controller.go, cmd/thv-proxyrunner/app/run.go, cmd/thv/app/config.go, cmd/thv/app/run.go, pkg/workloads/manager.go
This is part of the 0.2.0 release.
=> Remove deprecated commands and flags

docs/registry/schema.json
Matching up the schema with #1117
=> Add custom_metadata to the registry schema

cmd/thv/app/restart.go, test/e2e/restart_test.go
=> Add group restart

cmd/thv/app/runtime.go, docs/cli/thv.md, docs/cli/thv_runtime.md
=> Remove duplicate runtime command

pkg/client/config_editor.go, pkg/client/config_editor_test.go
Fix bug in `ensurePathExists()` in pkg/client/config_editor.go where json keys containing "." would never be found, causing an empty config path to always be returned in this case.
The gjson package treats "." as a special traversal character, so when building the retrieval path, escape this character as `\.` whenever it appears in json keys in the client config.
The hujson package treats "." as an ordinary character, so don't apply any special handling when building the patch path.
Finally, unit testing revealed a bug where passing a path of "/" (root path) causes hjson to attempt to always add a new key/value pair `"": {}`. Fix this by handling the root path as a special case, short circuiting all the traversal and patching logic.
Closes #1256.
=> Support client configs with "." in json keys

pkg/registry/data/registry.json
The source code of the MCP can be found [here](https://github.com/StacklokLabs/plotting-mcp)
=> Add plotting-mcp server to the registry

pkg/registry/data/registry.json
=> fix: aws-cost-analysis registry typo

pkg/container/templates/templates_test.go
This PR makes the unit tests in `pkg/container/templates` more resilient to version upgrades by using regex patterns instead of hardcoded version strings.
- Updated `templates_test.go` to use regex patterns for matching Docker base image versions
- Added a new `wantMatches` field to test cases for regex pattern matching
- Replaced hardcoded version checks (e.g., `FROM python:3.12-slim`) with regex patterns (e.g., `FROM python:\d+\.\d+-slim`)
- Tests now check for version-agnostic patterns for all Docker base images:
- Python: `FROM python:\d+\.\d+-slim`
- Node: `FROM node:\d+-alpine`
- Go: `FROM golang:\d+\.\d+-alpine`
- All existing tests pass with the current template versions
- Verified resilience by temporarily changing template versions and confirming tests still pass
- Ran: `go test …
=> Make template tests resilient to version upgrades

pkg/client/config_test.go
=> Prevent config tests from modifying real config

pkg/workloads/statuses/status.go, pkg/workloads/statuses/status_test.go, test/e2e/helpers.go, test/e2e/unhealthy_workload_test.go
This switches on the file-based state tracking.
=> Enable state tracking in status files

cmd/thv-operator/controllers/mcpserver_controller.go, cmd/thv-operator/controllers/mcpserver_pod_template_test.go
Set secure security context for ProxyRunner deployments. #1285
=> Add security context for ProxyRunner deployments (#1285)

CLAUDE.md
This should hopefully encourage Claude to not create PRs with conventional commit formats.
=> Add CONTRIBUTING.md to CLAUDE.md

test/e2e/proxy_stdio_test.go, test/e2e/telemetry_middleware_e2e_test.go
This is intended to provide greater test coverage to ensure that our middleware works as expected.
=> Add e2e for telemetry middleware

.github/workflows/claude.yml
This PR adds the basic claude code pr action that allows us to use it on PRs and issues. This is a test to see if it works and adds value, if not, we will investigate why, otherwise we will bench this and revisit it later.
Ref: https://github.com/stacklok/toolhive/issues/642
=> adds basic claude code pr action

pkg/registry/data/registry.json
=> Ensure all dockyard containers have provenance info set.

cmd/thv/app/client.go, cmd/thv/app/ui/clients_status.go, pkg/api/v1/discovery.go, pkg/client/config.go, pkg/client/config_test.go, pkg/client/discovery.go, pkg/client/discovery_test.go, pkg/client/migration.go, test/e2e/client_test.go
Update `thv client list-registered` to show associated groups if there are any.
Update `thv client status` to show a client as registered if it's registered in a group.
=> Take groups into account when listing clients

test/e2e/audit_middleware_e2e_test.go
Ensures that we test the audit middleware in our tests.
=> e2e test for audit middleware

pkg/networking/http_client.go
When deploying a dev KC instance, it is sometimes needed to set INSECURE_DISABLE_URL_VALIDATION because the KC instance won't be using TLS. We didn't honor INSECURE_DISABLE_URL_VALIDATION in the round-tripper which was causing http://keycloak and similar URLs to be rejected during connection even if they parsed fine.
=> Disable validating transport if INSECURE_DISABLE_URL_VALIDATION is set

pkg/updates/checker.go, pkg/updates/checker_test.go
Attempts to recover from a corrupted updates.json file while preserving the instance_id. Investigation as to the origin of the corruption is ongoing.
=> Attempt to recover from corrupted updates.json file

cmd/thv/app/run.go, cmd/thv/app/run_flags.go, cmd/thv/app/run_test.go, docs/cli/thv_run.md
=> remove the --remote flag while running remote server for better user experience

.github/ISSUE_TEMPLATE/add-an-mcp-server.md, .github/workflows/update-registry.yml, cmd/regup/app/root.go, docs/registry/management.md, docs/registry/schema.md
This PR migrates the ToolHive registry functionality away from the local `pkg/registry/data/registry.json` file to use the new [toolhive-registry](https://github.com/stacklok/toolhive-registry) repository, which distributes the registry via GitHub release artifacts.
- **Removed**: `regup` automation that updated individual server metadata
- **Added**: Daily sync from toolhive-registry releases
- **Enhanced**: Checksum verification using SHA256 hashes
- **Improved**: Better validation and error handling using `gh` CLI
- **Added**: Comprehensive PR descriptions with server counts and verification status
- **Added**: Deprecation warnings and migration notices
- **Kept**: Command available for local development and manual operations
- **Updated**: Help text to point to new repository …
=> Migrate registry to external toolhive-registry repository

pkg/config/registry.go
=> Always use absolute paths for setting registry conf files

test/e2e/protocol_builds_e2e_test.go
This PR adds comprehensive e2e tests for the `uvx://` protocol scheme, following the same pattern as the existing `npx://` protocol tests.
- ✅ **New e2e test for uvx protocol**: Tests successful build and startup of `arxiv-mcp-server` using `uvx://arxiv-mcp-server`
- ✅ **Tool verification**: Verifies all expected tools are available (`search_papers`, `download_paper`, `list_papers`, `read_paper`)
- ✅ **Error condition test**: Includes error condition test (currently skipped due to uvx build behavior differences)
- ✅ **Consistent pattern**: Follows the same structure and approach as existing npx protocol tests
The test successfully validates that:
- The uvx protocol integration works correctly with Python-based MCP servers from PyPI
- Docker image builds successfully using the uvx template …
=> Add e2e test for uvx protocol using arxiv-mcp-server

cmd/thv/app/run.go
Implements proper configuration persistence for `--from-config` and improves flag validation to automatically reject any other flags.
- **Config persistence**: Added `runConfig.SaveState(ctx)` to persist imported configurations to standard state directory
- **Flag validation**: Uses `flag.Changed` to dynamically detect conflicting flags
```bash
$ thv run --from-config myconfig.json --transport stdio --name test
Error: --from-config cannot be used with other configuration flags: [--transport --name]
```
Imported configs are now saved to state directory and manageable with other thv commands.
=> Add config persistence for --from-config and improve flag validation

test/e2e/protocol_builds_e2e_test.go
This PR adds an end-to-end test that validates building and running a Go-based MCP server using the go:// protocol scheme.
Summary:
- Adds a new go:// E2E case to protocol_builds_e2e_test.go using the OSV MCP server: go://github.com/StacklokLabs/osv-mcp/cmd/server@latest
- Verifies dynamic image build through ToolHive’s protocol scheme, server startup, and tools listing (query_vulnerability)
- Uses Streamable HTTP transport in alignment with current MCP guidance
Why:
- Complements existing uvx and npx protocol scheme tests, ensuring parity for Go builds
- Exercises the Dockerfile template generation for the Go transport and validates runtime behavior
Reference:
- ToolHive docs: https://docs.stacklok.com/toolhive/guides-cli/run-mcp-servers
Branch:
- feat/e2e-go-protocol-build
=> Add e2e test for go:// protocol build with osv-mcp (Streamable HTTP)

cmd/thv/app/secret.go, pkg/secrets/keyring/composite.go
=> Remove prefix from `thv secret get`

docs/cli/thv_run.md
=> We missed adding documentation for the CLI changes that came with OTEL

.github/workflows/claude.yml, .github/workflows/e2e-tests.yml, .github/workflows/image-build-and-publish.yml, .github/workflows/issue-triage.yml, .github/workflows/lint-helm-charts.yml, .github/workflows/lint.yml, .github/workflows/operator-ci.yml, .github/workflows/releaser-helm-charts.yml, .github/workflows/releaser.yml, .github/workflows/test-helm-charts.yml, .github/workflows/test.yml, .github/workflows/update-docs-website.yml, .github/workflows/update-registry.yml, .github/workflows/verify-docgen.yml, .github/workflows/verify-gen.yml
This sets up human readable names and identifiers for all our CI jobs.
=> Tidy up CI names and identifiers

pkg/testkit/testkit_test.go
I forgot to port this last test.
=> Port testkit test to testkit client
