stacklok/toolhive

- cmd/thv/app/registry.go
- pkg/registry/registry.go
- pkg/registry/types.go
We were printing the container image instead of the name, which is not
ideal. This fixes that.
Closes: https://github.com/StacklokLabs/toolhive/issues/154
> Fix printing MCP tool name when doing registry list

- cmd/thv/app/version.go
- cmd/thv/main.go
- go.mod
- pkg/updates/checker.go
- pkg/updates/checker_test.go
- pkg/updates/client.go
- pkg/versions/version.go
This PR introduces logic to check for new releases of ToolHive on startup. The logic work as follows:
1. On first run, an `updates.json` file is created alongside the config file. This contains an instance UUID, and the version returned from the API lookup.
2. On subsequent runs - check the file modification time of updates.json. a. If it's more than four hours old, call to the API, and update the updates.json file with the version returned. Notify the user if a new version is ready. b. If less than four hours old, compare the current version to the cached version from updates.json. Notify the user if an update is available. Skip calling the API.
> Call to update service on startup

- cmd/thv/app/run.go
- docs/cli/thv_run.md
- pkg/permissions/profile.go
- pkg/runner/config.go
- pkg/runner/config_test.go
The built-in permission profile was misnamed, `none` is a better name
for it, since it provides full isolation and no permissions.
This also sets the permission profile names as constants.
> Rename `stdio` permission profile to `none`

- README.md
- cmd/thv/app/run.go
- cmd/thv/app/run_protocol.go
- pkg/container/docker/client.go
- pkg/container/kubernetes/client.go
- pkg/container/runtime/types.go
- pkg/container/templates/npx.tmpl
- pkg/container/templates/templates.go
- pkg/container/templates/templates_test.go
- pkg/container/templates/uvx.tmpl
- pkg/runner/config_test.go
This allows ToolHive to dynamically run uv or npm based MCP servers without requiring them to be containerized. The premise is that we're able to detect if you use a transport protocol prefix to the MCP reference, and build a container image dynamically out of that. This way, you don't need to install `uv` or `npm` in your host to run MCP servers.
Do `thv run npx://<NPM package without the @ prefix>` or `thv run uvx://<package name>` to run them.
Related-to: #160
> Dynamically run npm/uv based MCP servers

- go.mod
- go.sum
- pkg/environment/environment.go
- pkg/runner/config.go
- pkg/secrets/encrypted.go
- pkg/secrets/factory.go
- pkg/secrets/types.go
- pkg/updates/checker.go
- pkg/updates/client.go
Some other refactoring, including renaming secrets.Manager to secrets.Provider for the sake of consistency.
> Use semver comparison for update checking

- pkg/updates/checker.go
This will tell the user if there is an update available based on the previous cached response.
> Fix previous version check

- cmd/thv/app/run.go
- cmd/thv/app/run_common.go
Cobra was swalling the command line arguments, so I resorted back to
using os.Args. Subsequently, we were missing the `--` from the container
run in detached mode. This should fix things up in a way that containers
now get the right arguments.
Closes: #170
> Fix command processing

- .goreleaser.yaml
- Taskfile.yml
The files were moved around without applying the changes to the ldflags sections. This fixes that.
Fixes: #153
> Fix the version command regression

- deploy/k8s/README.md
- deploy/k8s/namespace.yaml
- deploy/k8s/rbac.yaml
- deploy/k8s/thv.yaml
This commit adds dedicated RBAC resources for toolhive:
- Created a ServiceAccount for toolhive
- Created a Role with the necessary permissions for StatefulSets, Services, Pods, and Pod attachments
- Created a RoleBinding to bind the Role to the ServiceAccount
- Updated the StatefulSet in thv.yaml to use the new ServiceAccount
- Added a namespace.yaml file for deploying toolhive in a dedicated namespace
- Added a README.md with deployment instructions and options
These changes improve security by replacing the overly permissive cluster-admin role
with a more restricted role that has only the necessary permissions for toolhive to function.
Closes: #102
> Add Kubernetes RBAC resources for toolhive

- docs/authz.md
- pkg/authz/cedar.go
- pkg/authz/cedar_entities_test.go
- pkg/authz/cedar_entity.go
This commit enhances the Cedar authorization framework to properly handle
JWT claims and tool arguments:
1. JWT claims are now added to the principal entity and are accessible via
`principal.claim_*` in Cedar policies.
2. Tool arguments are now added to the resource entity and are accessible via
`resource.arg_*` in Cedar policies.
3. Both claims and arguments are also available in the context and are
accessible via `context.claim_*` and `context.arg_*` in Cedar policies.
4. Updated the documentation to reflect these changes and provide examples
of both entity-based and context-based access to claims and arguments.
5. Updated the tests to properly use the new `CreateEntitiesForRequest`
function signature, which now takes both `claimsMap` and `attributes`
parameters.
These changes make the …
> authz: Enhance Cedar authorization framework

- pkg/transport/proxy/httpsse/http_proxy.go
- pkg/transport/proxy/transparent/transparent_proxy.go
- pkg/transport/stdio.go
- pkg/transport/types/transport.go
This commit removes the unused response channel from the transport proxy
implementation. The response channel was being written to in the
parseAndForwardJSONRPC function but was never consumed anywhere in the
codebase.
This change prevents potential memory issues from the channel filling up
and eliminates unnecessary error logs when the channel becomes full,
while maintaining the primary message flow between clients and containers.
> refactor: remove unused response channel

- docs/authz.md
- pkg/authz/config.go
This change adds support for reading CedarConfig from YAML files in addition to
the existing JSON support. The implementation includes:
1. Adding YAML tags to the Config and CedarConfig structs
2. Modifying the LoadConfig function to detect file format based on extension
3. Updating documentation to reflect YAML support
This enhancement provides more flexibility for users who prefer YAML over JSON
for configuration files.
> feat(authz): Add YAML support for CedarConfig

- cmd/thv/app/registry.go
- cmd/thv/app/run.go
- pkg/registry/types.go
This change adds a TargetPort field to the Server struct in the registry
package. This allows specifying the target port in the registry, which is
particularly useful for SSE transport mode where we need to know what port
the SSE server is going to be listening on.
This makes the registry more portable and flexible, especially for SSE servers
that need to expose specific ports.
> registry: Add target port to Server struct

- cmd/thv/app/run.go
- pkg/registry/types.go
This change implements the functionality to use the Args field from the Server struct in the MCP registry. When an MCP server is run, any arguments defined in the registry entry will be prepended to the command-line arguments provided by the user.
> feat: Use server Args from registry

- pkg/registry/data/registry.json
This commit adds the NetBird MCP server to the registry.json file. NetBird is a
Model Context Protocol (MCP) server that provides access to NetBird network
management capabilities.
The server is configured with:
- SSE transport mode on port 8001
- Required NETBIRD_API_TOKEN environment variable
- Optional NETBIRD_HOST environment variable
- Seven tools for managing NetBird networks, peers, groups, and policies
GitHub repository: https://github.com/aantti/mcp-netbird
> Add NetBird MCP server to registry

- pkg/registry/types.go
Improve the documentation in pkg/registry/types.go by adding detailed
comments to all fields in the Registry, Server, EnvVar, and Metadata structs.
> docs: add comprehensive documentation to registry types

- cmd/thv/app/registry.go
Sort the `registry list` outpub by name instead of image.
Closes #222
> Sort registry list by name instead of image

- cmd/thv/app/run.go
- docs/cli/thv_run.md
This should make it easier to run API-accessing MCPs.
> Change default permission profile to `network`

- cmd/thv/app/commands.go
- cmd/thv/main.go
Skip the update check for the `completion` command.
Previously, if the update check returned any output, it was included in the stdout content for the shell completions file, leading to shell errors when loading it.
Resolves #221
> Skip update check for completion command

- pkg/container/templates/templates_test.go
- pkg/container/templates/uvx.tmpl
This change improves compatibility and resolves permission issues with the uv package manager.
Ended up making this change prompted by some packages (like playwright) not working in alpine.
> Switch uvx template from Alpine to Debian-slim

- .github/workflows/update-registry.yml
This changes the timer of the registry update github workflow
to only trigger once a day. This ensures we don't have as many
PRs as we have now (one every hour). This also increases the
number of entries we update.
> Only run registry update once a day and update more

- cmd/thv/app/run.go
- docs/cli/thv_run.md
This commit improves the help message for the `run` subcommand to clearly
explain all three modes of operation:
1. Running an MCP server from the registry
2. Running an MCP server from a container image
3. Running an MCP server using a protocol scheme (uvx:// or npx://)
The help message now includes examples for each mode and accurately
describes what each protocol scheme does:
- uvx:// creates a Python container using the uv package manager
- npx:// creates a Node.js container using npx
This makes the help message more thorough, accurate, and user-friendly
while remaining concise and focused on the essential information.
> cmd/thv: Improve help message for run subcommand

- cmd/thv/app/run_protocol.go
Extract package name formatting logic into a dedicated function that handles
both path separators (/) and version specifiers (@) when generating Docker
image names. This ensures valid image names are created when using versioned
packages with protocol schemes.
> fix(run): allow for versioned packages in protocl-based runs

- README.md
Update the README.md file to reflect the renaming of the stdio permission profile to 'none'.
This change aligns with PR #166 where the profile was renamed to better reflect its purpose
of providing full isolation with no permissions.
> docs: Update README to reflect renaming of stdio profile to none

- .github/workflows/operator-ci.yml
- cmd/thv/app/constants.go
- cmd/thv/app/search.go
This PR fixes two issues:
1. Adds the missing `workflow_call` trigger to the operator-ci.yml workflow file, which allows it to be called from other workflows like run-on-pr.yml and run-on-main.yml. This fixes the CI error: "workflow is not reusable as it is missing a `on.workflow_call` trigger".
2. Creates a new constants.go file with output format constants (FormatJSON and FormatText) and updates search.go to use these constants instead of string literals. This fixes the linting issue: "string `json` has 4 occurrences, make it a constant (goconst)".
- Added `workflow_call` trigger to .github/workflows/operator-ci.yml
- Created cmd/thv/app/constants.go with format constants
- Updated cmd/thv/app/search.go to use the constants
- Verified that the linter runs successfully with no issues
- …
> Fix workflow and linting issues

- README.md
- cmd/thv/app/run.go
- cmd/thv/app/run_protocol.go
- docs/cli/thv_run.md
- pkg/container/templates/go.tmpl
- pkg/container/templates/templates.go
- pkg/container/templates/templates_test.go
This PR adds support for the go:// transport protocol, which allows running Go-based MCP servers using the Go toolchain.
- Added a new template file `pkg/container/templates/go.tmpl` that uses the golang:1.24-alpine image
- Added a new transport type constant `TransportTypeGO` in the templates package
- Updated the template handling functions to support the new go transport type
- Added a new protocol scheme constant `GOScheme` in the run_protocol.go file
- Updated the protocol scheme handling to support the new go:// protocol
- Updated the help text in run.go to include the new go:// protocol in the documentation
- Updated the README.md to include information about the new go:// protocol
- Added tests for the new go transport type
```bash
thv run …
```
> Add go:// transport protocol for golang containers

- pkg/container/docker/client.go
There were errors when trying to ping the podman runtime when there is a socketpath detected. This PR ensures that if there is a failure in the ping to the runtime, it will skip to the next eligible runtime (docker in this case).
I've made sure to:
- loop through supported socketpaths, checking if they exist and connect to them
- added the `err != nil` code paths in the socketpath checks because we were swallowing them by only executing code on the `err == nil` cases. this allows us to log the reasons why it failed.
Screenshot of `thv` finding a Podman socketpath, trying to connect to it (because I've stopped it), failing, and trying docker instead, which resulted in a successful connection.
Ref:  https://github.com/StacklokLabs/toolhive/issues/260
> fix: fixes the lack of fallback to docker

- .github/workflows/image-build-and-publish.yml
- .github/workflows/releaser.yml
This PR modifies the image build workflow to push the 'latest' tag only when building from a tag or release. It also adds an image build and push job to the releaser workflow.
> ci: Push latest tag only when building from a tag or release

- cmd/thv-operator/README.md
- cmd/thv-operator/controllers/mcpserver_controller.go
- deploy/operator/operator.yaml
- deploy/operator/toolhive_rbac.yaml
This PR implements the principle of least privilege by:
1. Using the toolhive service account for MCP server pods instead of the default one
2. Adding a check to update existing deployments to use the correct service account
3. Updating the README to include applying the toolhive_rbac.yaml file
4. Updating the operator image reference to use the latest version
These changes ensure that the pods created by the operator have only the permissions they need to function properly, reducing the potential attack surface.
> Use toolhive service account for MCP server pods

- deploy/operator/samples/mcpserver_fetch.yaml
Currently, for the operator, you need to install the MCPServer in the same namespace.
> adds toolhive namespace for sample

- pkg/secrets/factory.go
Closes https://github.com/StacklokLabs/toolhive/issues/244
```
thv secret set gh-auth-token
A new version of ToolHive is available: v0.0.22
Currently running: v0.0.22-4-gd155196-dirty
Enter secret value (input will be hidden): 
ToolHive needs a password to secure your credentials in the OS keyring.
This password will be used to encrypt and decrypt API tokens and other secrets
that need to be accessed by MCP servers. It will be securely stored in your OS keyring
so you won't need to enter it each time.
Please enter your keyring password: 9:33PM INF 
9:33PM INF writing password to os keyring
Secret gh-auth-token set successfully
```
> Enhance the message about keyring password usage for transparency

- cmd/thv-operator/controllers/mcpserver_controller.go
- deploy/operator/operator.yaml
- pkg/container/kubernetes/client.go
It appears that the issue seems to be that we create a [SVC via the Operator](https://github.com/StacklokLabs/toolhive/blob/main/cmd/thv-operator/controllers/mcpserver_controller.go#L136-L157) and then in the toolhive code we create a [headless SVC](https://github.com/StacklokLabs/toolhive/blob/main/pkg/container/kubernetes/client.go#L326) if the transport type is sse.
This ends up with the scenario where the toolhive container is trying to create a service with `ClusterIP: None`, however because the SVC has already been created by the Operator, it errors because the ClusterIP field is immutable and cannot be changed. In this PR we add explicit names to both services created by ToolHive.
This includes:
- The Proxy Service created by the Operator
- The Headless Service created by the …
> fix: explicit naming for Kuberentes Services for Proxy and MCP server

- Taskfile.yml
- deploy/k8s/ingress.yaml
- docs/kind/ingress.md
- docs/running-toolhive-in-kind-cluster.md
We had Ingress documentation buried in a toolhive guide. So this PR:
- Separates the Kind ingress setup as a separate document so that it can be referred to later on
- Refactor some Task file to make them runnable on their own
- Added a better Ingress example with new svc name changes in ToolHive (headless vs proxy)
> docs: adds separate ingress docs and minor refactor

- cmd/thv-operator/controllers/mcpserver_controller.go
When the Operator tries to create the svc, it tries to find it first. In this case, it couldn't find it because it was using the wrong name for lookup. It then tried to create it with the correct name, and was erroring because it already existed.
This commit ensures that it uses the correct name for lookup, so that it doesn't try to create an already existing service.
> fix: ensures the service lookup uses the correct name

- Taskfile.yml
With a multi line cmd, we are able to run multiple commands in the same shell. this allows the CA to be defined and used.
> fix: CA variable not persisted between commands

- README.md
- cmd/thv/app/config.go
- docs/cli/thv_config_register-client.md
- docs/cli/thv_config_remove-client.md
- pkg/client/config.go
- pkg/client/config_test.go
- pkg/config/config_test.go
Claude Code now supports SSE MCP servers. This PR adds the ability to register `claude-code` as Client, and makes sure that the auto-discovery can discovery the [user scoped](https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/tutorials#understanding-mcp-server-scopes) `.claude.json` file.
Ref: https://github.com/StacklokLabs/toolhive/issues/318
> feat: Claude Code Client Support

- pkg/versions/version.go
This ensures we have the VCS info even on `dev dev` cases, which is when
the TOOLHIVE_DEV environment variable is set up.
> Set up VCS for anything starting in dev

- cmd/thv/app/run.go
This actually leverages the transport specified by the registry. This
had probably not been an issue since there's not many SSE servers in our
registry.
Closes https://github.com/StacklokLabs/toolhive/issues/337
> Respect transport from registry when running

- deploy/k8s/thv.yaml
- pkg/container/kubernetes/client.go
- pkg/container/kubernetes/client_test.go
Closes https://github.com/StacklokLabs/toolhive/issues/92
> Implement Security Contexts for Kubernetes MCP Servers 

- cmd/thv/app/config.go
- cmd/thv/app/list.go
- cmd/thv/app/logs.go
- cmd/thv/app/proxy.go
- cmd/thv/app/restart.go
- cmd/thv/app/rm.go
- cmd/thv/app/run.go
- cmd/thv/app/stop.go
- pkg/lifecycle/manager.go
In order to allow the functionality of THV to be called from the CLI or REST API, we need to move business logic out of the implementation of the CLI. This PR is a first step which takes the rm, stop and list commands and moves them into a high-level "lifecycle" package. Various refactoring has been carried out to remove duplicated code.
Work for future PRs:
1) Move run and restart here. This will need refactoring of the code for
starting a THV container.
2) Unit tests for the functionality in this package.
3) Refactoring some logic out of this lifecycle package, for example,
proxy and client config management functions.
> Begin refactoring container lifecycle logic out of CLI

- cmd/thv/app/run_common.go
Removes an extra log message in `thv run` ouput that shouldn't be there.
> Remove extraneous log message

- cmd/thv/app/run.go
- pkg/runner/protocol.go
Since this logic will be reused by the API, move it inside the pkg package.
One minor piece of refactoring: Get rid of the `logDebug` function - the logger code sets the log level to debug if the `--debug` flag is passed to the CLI, so this should not be necessary.
> Move runner protocol code into pkg

- cmd/thv/app/run_common.go
- pkg/process/detached.go
- pkg/runner/runner.go
- pkg/secrets/encrypted.go
- pkg/secrets/factory.go
Enforcing this invariant to simplify some upcoming changes. This also refactors the logic for detecting if we are in a detached processes.
> Ensure that we do not prompt for passwords in detached mode

- Taskfile.yml
This stops building multi-arch images in the local `ko` build. This will
make local builds a lot faster. It also changes the image reference to
use the one we build upstream.
> Change Taskfile for lighter ko builds

- cmd/thv/app/commands.go
- cmd/thv/main.go
This ensures that we have a valid logger when needed. And it addresses
the issue reported by Andrew Block in #342 where we'd segfault.
The segfault was actually not because of the user being different, but
because we were trying to log an error on a logger that's nil.
> Initialize logger on command run

- cmd/thv/app/commands.go
- cmd/thv/app/server.go
- docs/cli/thv.md
- docs/cli/thv_serve.md
- go.mod
- go.sum
- pkg/api/server.go
- pkg/api/v1/healtcheck_test.go
- pkg/api/v1/healthcheck.go
- pkg/api/v1/version.go
- pkg/api/v1/version_test.go
- pkg/logger/logger.go
This PR adds a `serve` command along with scaffolding for the API. Two basic endpoints are provided - a healthcheck, and a version endpoint.
The HTTP server is not yet integrated with logging - I think we need to consider getting rid of our own logging interface and use something like zerolog instead.
> Add initial API server to ToolHive

- pkg/lifecycle/manager.go
- pkg/runner/runner.go
If you run `thv run uvx://mcp-server-fetch` then the server name thats inserted into the mcp server client config isn't actually the server name that you get from `thv list`. This PR fixes that by using the correct name.
In addition, it was spotted that in the case where you run the above command, the `thv stop` output was empty in the run log line:
```log
2:17PM INF Use 'thv stop []' to stop the server
```
This was because we are only setting the value if the `--name` isn't empty. In this case it is, so the fix here is to use the `containerName` if it is not nil.
Results:
```log
2:17PM INF Use 'thv stop [toolhivelocal-uvx-mcp-server-fetch-1747135035]' to stop the server
```
Ref: https://github.com/stacklok/toolhive/issues/360
> fix: use correct container name when updating mcpServer client config and display stop command

- pkg/lifecycle/manager.go
- pkg/transport/proxy/manager.go
Group some of the proxy logic which previously lived inside the lifecycle package. In future, we may want to build a proxy process manager interface.
> Move proxy-related code into its own package

- pkg/api/v1/version_test.go
- pkg/updates/checker.go
- pkg/versions/version.go
Previously the application defaulted to a version of "dev" when building thv from source. Change the logic to manufacture a version string consisting of "build-" followed by the first eight characters of the commit SHA. If the commit SHA is unavailable, the version will be "build-unknown".
As part of this change, the update checking logic will print a more meaningful message instead of blindly telling the user that an update is available.
> Improve version handling for local builds

- pkg/container/docker/client.go
This update enhances the Docker client to support runtime-specific socket paths through environment variables `TOOLHIVE_DOCKER_SOCKET` and `TOOLHIVE_PODMAN_SOCKET`. The implementation validates the provided socket paths and returns the appropriate runtime type. If the socket path is invalid or not found, an error is returned.
This feature enables managing MCP servers on remote machines through SSH socket forwarding. Here's how to use it:
1. Create an SSH config file (`ssh_config`):
```ssh
Host docker-remote
HostName <remote-server>
User <remote-user>
LocalForward /tmp/remote-docker.sock /var/run/docker.sock
NoHostAuthenticationForLocalhost yes
RequestTTY no
ExitOnForwardFailure yes
PermitLocalCommand no
ServerAliveInterval 60
ServerAliveCountMax 3
```
2. Start an SSH tunnel to forward the …
> feat: add support for custom container socket paths in Docker client

- cmd/thv/app/list.go
- cmd/thv/app/registry.go
- cmd/thv/app/version.go
- docs/cli/thv_version.md
- pkg/updates/checker.go
This PR fixes the issues reported in #384:
- Makes format flags consistent by using `--format json` across all commands
- Maintains backward compatibility with `--json` for the version command
- Ensures JSON output goes to stdout instead of stderr
- Moves update check messages to stderr
- Improves JSON formatting using encoding/json
Fixes #384
> Fix JSON output inconsistencies across commands

- cmd/thv/app/run.go
- cmd/thv/app/run_common.go
- cmd/thv/app/server.go
- pkg/api/server.go
- pkg/api/v1/servers.go
- pkg/secrets/types.go
This implements the API for starting MCP servers. An MCP server can be started with as little as:
```
curl -XPOST -v localhost:8080/api/v1beta/servers --header "Content-Type: application/json" --data '{"image": "fetch"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 53812 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> POST /api/v1beta/servers HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 18
>
* upload completely sent off: 18 bytes
< HTTP/1.1 200 OK
< Date: Fri, 16 May 2025 17:57:41 GMT
< Content-Length: 28 …
```
> Implement endpoint for starting MCP servers

- cmd/thv/app/config.go
- cmd/thv/app/list.go
- cmd/thv/app/proxy.go
- cmd/thv/app/run.go
- docs/cli/thv_proxy.md
- docs/cli/thv_run.md
- pkg/api/v1/servers.go
- pkg/lifecycle/manager.go
- pkg/runner/config.go
- pkg/runner/config_test.go
- pkg/runner/runner.go
- pkg/transport/factory.go
- pkg/transport/proxy/httpsse/http_proxy.go
- pkg/transport/proxy/transparent/transparent_proxy.go
- pkg/transport/sse.go
- pkg/transport/stdio.go
The following PR adds support for the `--host` CLI flag which should make the host address of the proxies configurable. 
Unfortunately I was not able to reproduce this issue in the first place on my machine, so I'll appreciate a more detailed review or if someone can reproduce it on their side it would be even better.
Related: #362
> Add support for --host flag

- pkg/transport/stdio.go
- pkg/transport/stdio_test.go
fixes #379
Added handling for the Unicode replacement character (\uFFFD) in JSON-RPC message processing. This character appears when there's invalid UTF-8 encoding in the input and was causing JSON-RPC message decoding errors. The fix ensures proper sanitization of input messages before parsing.
> fix: handle replacement character in JSON-RPC messages

- .gitignore
- Taskfile.yml
- deploy/operator/operator_local.yaml
before we weren't building the toolhive image when deploying a local operator to kind, this resulted in the operator always deploying the latest toolhive runtime image. this PR ensures to build the toolhive runtime image AND deploy it when using kind to deploy the operator
> feat: adds missing local toolhive image build for kind

- cmd/thv-operator/Taskfile.yml
The following PR fixes a segfault - 
```bash
You are running a local build of ToolHive, latest release is: v0.0.33
11:49AM INF Processed cmdArgs: [[]]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1faa79a]
goroutine 1 [running]:
github.com/stacklok/toolhive/cmd/thv/app.verifyImage({0x2a9bcd0?, 0x488ec00?}, {0x7ffffffffc9e?, 0xc00070e270?}, {0x2ab1948?, 0xc00070e270?}, 0x0, {0x26d5199, 0x4})
github.com/stacklok/toolhive/cmd/thv/app/run.go:326 +0x37a
github.com/stacklok/toolhive/cmd/thv/app.runCmdFunc(0x48426a0, {0xc0000ae1c0, 0x1, 0x26d5181?})
github.com/stacklok/toolhive/cmd/thv/app/run.go:246 +0xdfb
github.com/spf13/cobra.(*Command).execute(0x48426a0, {0xc0000ae0e0, 0x7, 0x7}) …
```
> Do not pin the platform for ko builds

- cmd/thv-operator/Taskfile.yml
- deploy/charts/operator/templates/deployment.yaml
- deploy/charts/operator/values.yaml
Up to now using `task` and `kind` we've installed the toolhive operator via yaml manifests in combination with `ko resolve` to replace the image references with locally built image reference. With this PR we move towards a helm install instead so that we can start utilising the helm charts for more customisability for deployments using helm values.
Ref: https://github.com/stacklok/toolhive/issues/314
> feat: completes local toolhive operator helm install for task

- .github/workflows/releaser-helm-charts.yml
The `charts_dir` option didn't seem to matter in the `cr.yaml`.  trying it for the action instead
> fix: adds charts_dir option to action

- cmd/thv/app/run.go
- pkg/runner/protocol.go
The following PR fixes a bug where in the event of running servers through a protocol scheme we were overwriting the initial image which made some of the follow up checks obsolete causing errors.
> Fix wrong image handling

- .codespellrc
The following PR updates .codespellrc rules to skip *.mod and *.sum files
> Update .codespellrc rules to skip *.mod and *.sum files

- cmd/thv/app/server.go
- docs/cli/thv_serve.md
- pkg/api/server.go
fixes #410 
Exposes toolhive server via UNIX socket. Providing a --socket argument to the `thv serve` command overrides the host:port address with the provided socket.
Example usage:
`/thv serve --socket /tmp/toolhive.sock`
`curl --unix-socket /tmp/toolhive.sock http://localhost/api/v1beta/version`
`{"version":"build-42ad77b0"}`
> feat: Exposes toolhive server via a UNIX socket

- pkg/container/verifier/verifier.go
The following PR makes the base provenance properties optional so one can enforce only the ones they are interested in.
> Make the base provenance properties optional

- pkg/registry/data/registry.json
The following PR adds the ocireg-mcp server to the registry.
Verified via `thv run oci-registry` -
> Add ocireg-mcp server to the registry

- cmd/thv/app/logs.go
- docs/cli/thv_logs.md
- pkg/container/docker/client.go
- pkg/container/kubernetes/client.go
- pkg/container/runtime/types.go
This updates the `--tail` flag for `thv logs` to `--follow`, to align with the expected behavior from `docker logs`.
> Change thv logs --tail flag to --follow

- cmd/thv/app/logs.go
- docs/cli/thv_logs.md
I missed updating the short form for `thv logs --follow` from `-t` to `-f` in #452
> Fix the short form of logs --follow

- cmd/thv/app/commands.go
- cmd/thv/app/run.go
- cmd/thv/main.go
* Silence showing the usage on error
* Fail on forced image verification
* Removes a duplicated error message being printed
> Silence showing the usage on error and fail on forced image verification

- cmd/thv/app/commands.go
- pkg/container/factory.go
The following PR skips the update checks when running inside Kubernetes.
> Skip update checks in Kubernetes

- .github/workflows/releaser-helm-charts.yml
The following PR fixes an issue with the release process of the helm charts which was causing the update check flow to return wrongful data. 
The root cause is we were marking the helm chart release as latest which was overwriting the previous toolhive release which resulted in wrong processing on update checks both on the client and on the server side.
> Fix setting the helm chart GitHub release as latest

- README.md
- cmd/thv/app/config.go
- docs/cli/thv_config.md
- docs/cli/thv_config_get-registry-url.md
- docs/cli/thv_config_set-registry-url.md
- docs/cli/thv_config_unset-registry-url.md
- pkg/config/config_test.go
https://github.com/stacklok/toolhive/pull/423 added support for configurable remote MCP registries. In response to [this comment](https://github.com/stacklok/toolhive/pull/423#issuecomment-2913212769), this PR adds documentation to the README as well as 3 new `config` commands:
* `set-registry-url <url>`: Set the URL for the remote MCP server registry.
* `get-registry-url`: Display the URL of the remote registry that is currently configured
* `unset-registry-url`: Remove the registry URL configuration, reverting to the built-in registry
Are adding 3 separate subcommands to `thv config` okay here or would we prefer using a different set CLI subcommands?
> Add ability to set, get, and unset registry URLs

- pkg/runner/protocol.go
Converts the generated image name to lowercase for Docker compatibility.
Fixes issue with mixed-case protocol URIs, for example a Go module in a repo with mixed-case org name.
Previously:
```bash
$ ./bin/thv run --name osv --transport sse go://github.com/StacklokLabs/osv-mcp/cmd/server@latest
5:14PM INF Processed cmdArgs: [[]]
5:14PM INF Building Docker image for [go github.com/StacklokLabs/osv-mcp/cmd/server] package: %!s(MISSING)
5:14PM INF Building image [toolhivelocal/go-github-com-StacklokLabs-osv-mcp-cmd-server:20250529171420 /var/folders/qc/rrhc78216yg6x990srv7szfh0000gn/T/toolhive-docker-build-1602286757] from context directory %!s(MISSING)
Error: failed to process protocol scheme: failed to build Docker image: Error response from daemon: invalid reference format: repository name …
```
> Fix protocol handler compatibility with mixed-case packages

- pkg/container/templates/templates_test.go
- pkg/runner/protocol.go
When running local Go MCP servers with the `go://` protocol, users encountered the error:
```
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```
This happened when running commands like:
```bash
thv run --name osv --transport sse go://./cmd/server
```
The issue was in the `setupLocalBuildContext` function in [`pkg/runner/protocol.go`](pkg/runner/protocol.go). When processing a local path like `./cmd/server`, the function was:
1. Setting the build context directory to the specific package directory (e.g., `/path/to/project/cmd/server`)
2. Using `COPY . /app/` in the Dockerfile, which only copied the contents of the `cmd/server` directory
3. This meant `go.mod` (located in the project root) was never copied into the container
4. When `go run …
> fix: Use current working directory as build context for local Go paths

- pkg/registry/data/registry.json
The MKP (`k8s`) server in the registry had a multi-line description, when no other servers did this. The extra info described mounting the kubeconfig file into the contianer; I hinted at this in the env var's description and users can go to the repo for more info.
A few other entries had 5 newlines at the end of their descriptions for some reason, so I removed those too.
Resolves #516
> Shrink the MKP MCP description in the registry

- cmd/thv-operator/Taskfile.yml
- docs/kind/deploying-mcp-server-with-operator.md
- docs/kind/deploying-toolhive-operator.md
- docs/kind/ingress.md
- docs/kind/setup-kind-cluster.md
- The changes rename the kind cluster consistently across docs and Taskfile configuration for better clarity.
- Also removes the `$` symbols from single line commands for easier copying and pasting
> Standardize kind cluster naming across documentation and operator configs

- docs/kind/deploying-mcp-server-with-operator.md
- docs/kind/ingress-port-forward.md
- Adds port-forward docs for Kind
- References how to setup ingress/port-forward in kind guides from the deploying MCP server with operator guide.
> docs: adds kind port-forward docs and adds references to ingress docs in operator

- Taskfile.yml
Fixes #518
A difference in path handling on macOS vs. Linux was causing the test-e2e task to fail:
```text
[FAILED] thv binary should be available
Unexpected error:
<*fmt.wrapError | 0x1400060e0c0>: 
thv binary not available at ./bin/thv: fork/exec ./bin/thv: no such file or directory
{
msg: "thv binary not available at ./bin/thv: fork/exec ./bin/thv: no such file or directory",
err: <*fs.PathError | 0x14000216e70>{
Op: "fork/exec",
Path: "./bin/thv",
Err: <syscall.Errno>0x2,
},
}
occurred
In [BeforeEach] at: /Users/dan/code/stacklok/toolhive/test/e2e/fetch_mcp_server_test.go:28 @ 05/31/25 14:08:17.223
```
Making THV_BINARY absolute fixes it.
> fix: resolve path error with test-e2e task on macOS

- cmd/thv-operator/controllers/mcpserver_controller.go
- cmd/thv-operator/main.go
- deploy/charts/operator/Chart.yaml
- deploy/charts/operator/README.md
- deploy/charts/operator/templates/clusterrole/role.yaml
- pkg/operator/telemetry/telemetry.go
- pkg/operator/telemetry/telemetry_test.go
- pkg/updates/client.go
- pkg/updates/client_test.go
The following PR adds support for update checks for the ToolHive operator. The telemetry runs every 4 hours and respects leadership changes, automatically stopping when leadership is lost.
**Details:**
- Add telemetry support for the ToolHive operator to periodically check for updates
- Implement leader election for telemetry operations to ensure only one instance performs checks
- Uses ConfigMaps to store instance IDs and last check timestamps
- Updated permissions to allow ConfigMap management for telemetry data
- Updated the version client to support adding a suffix to the user agent
> Initial support for update checks for toolhive operator

- pkg/logger/logger.go
The logger was showing problematic output:
- `Proxy process stopped !BADKEY=[]` when logging without arguments
- Format string errors like `%!s(int=20247)` and `%!d(MISSING)`
Global logging functions in `pkg/logger/logger.go` were incorrectly passing variadic arguments:
- `log.Info(msg, args)` instead of `log.Info(msg, args...)`
- This caused the entire slice to be passed as a single argument instead of expanding the elements
Fixed all global logging functions to properly expand variadic arguments:
- Changed `log.Method(msg, args)` to `log.Method(msg, args...)`
- Applied to all logging levels: Debug, Info, Warn, Error, Panic (both formatted and non-formatted)
- All existing tests pass
- No linting issues
- Verified fix resolves both `!BADKEY` and format string issues
- …
> fix(logger): resolve !BADKEY and format string issues

- pkg/registry/data/registry.json
This PR updates the Grafana MCP server entry in the registry to reflect the latest changes from the official repository at https://github.com/grafana/mcp-grafana.
- **Updated Docker image**: Changed from \`grafana/grafana-oss:latest\` to \`mcp/grafana:latest\` (official MCP server image)
- **Enhanced description**: Added Sift investigations functionality
- **Added new tools**: 
- \`list_teams\` (Admin functionality)
- \`update_dashboard\` (Dashboard management)
- \`get_dashboard_panel_queries\` (Dashboard analysis)
- \`get_investigation\`, \`get_analysis\`, \`list_investigations\` (Sift investigations)
- \`find_error_pattern_logs\`, \`find_slow_requests\` (Sift analysis tools)
- **Updated tags**: Added \`sift\`, \`investigations\`, \`oncall\`
- **Network permissions**: Updated for more …
> Update Grafana MCP server registry entry

- cmd/thv/app/proxy.go
- docs/cli/thv.md
- docs/cli/thv_proxy.md
This PR enhances the proxy OAuth authentication system with security hardening, improved code quality, and better user experience based on post-merge feedback for commit aeceaa7d4eb.
- ✅ **Secure credential handling**: Added `--remote-auth-client-secret-file` flag for file-based credential storage
- ✅ **Environment variable support**: Added `TOOLHIVE_REMOTE_OAUTH_CLIENT_SECRET` environment variable
- ✅ **Credential precedence**: Implemented secure resolution order (flag → file → env var)
- ✅ **Path validation**: Added `filepath.Clean()` validation for secure file handling
- ✅ **Enhanced logging**: Protected sensitive information while maintaining debuggability
- ✅ **Configurable timeouts**: Replaced hardcoded timeouts with named constants
- ✅ **Better error handling**: Comprehensive error …
> feat: harden proxy OAuth authentication with enhanced security and usability

- examples/operator/mcp-servers/mcpserver_mkp.yaml
We need to hardcode the serviceaccount name of the proxyrunner for now. Once we have implemented https://github.com/stacklok/toolhive/issues/654 this will not be needed anymore as the serviceaccounts will be created by the operator and the need for an override will not be necessary
> fix: corrects serviceaccount for mkp example

- pkg/authz/response_filter.go
- pkg/lifecycle/manager.go
- pkg/mcp/parser.go
The `filterToolsResponse` function was not being called in the authorization middleware chain, preventing proper filtering of tools/prompts/resources based on Cedar policies.
- **Problem**: The `--authz-config` flag wasn't being passed when processes detached
- **Solution**: Added the missing flag to detached process arguments in lifecycle manager
- **Impact**: Authorization middleware now gets properly configured in detached mode
- **Problem**: Parser only recognized `/messages` but requests came to `/message` (singular)
- **Solution**: Updated endpoint recognition to include both `/messages` and `/message`
- **Impact**: MCP requests are now properly parsed and available for authorization
- **Problem**: SSE-based responses return 202 with empty bodies, causing JSON parsing failures
- …
> Fix authorization middleware chain for filterToolsResponse

- cmd/thv/app/secret.go
- docs/cli/thv_secret_provider.md
- pkg/environment/environment_test.go
- pkg/runner/config_test.go
- pkg/secrets/1password.go
- pkg/secrets/encrypted.go
- pkg/secrets/types.go
This PR implements a capability system for secret providers to address the observed trend where different providers have different capabilities (e.g., 1Password being read-only while encrypted provider supports full read-write operations).
- **Added `ProviderCapabilities` struct** to define what operations each provider supports (read, write, delete, list, cleanup)
- **Updated `Provider` interface** to include `Capabilities()` method
- **Implemented capabilities for existing providers:**
- `encrypted`: Full read-write capabilities
- `1password`: Read-only capabilities (with future listing support planned)
- **Added capability checking** to CLI commands (`set`, `delete`, `list`) with helpful error messages
- **Updated provider command descriptions** to clearly indicate capability …
> feat: implement secret provider capability types

- pkg/workloads/manager.go
- test/e2e/fetch_mcp_server_test.go
- test/e2e/helpers.go
- test/e2e/inspector_test.go
- test/e2e/osv_authz_test.go
- test/e2e/osv_mcp_server_test.go
- test/e2e/proxy_oauth_test.go
Fixes #350 - Proxy processes were not being terminated when using `thv rm` command.
- **Fixed DeleteWorkload()**: Added `proxy.StopProcess()` call before stopping container to match the pattern used in `StopWorkload()`
- **Updated e2e tests**: Modified test helpers to properly check for errors in cleanup instead of ignoring them
- **Removed obsolete flag**: Removed `-f` flag usage in `StopAndRemoveMCPServer` helper as it no longer exists
The issue was that `DeleteWorkload()` was calling `stopContainer()` directly instead of following the same pattern as `StopWorkload()` which calls `proxy.StopProcess()` first to terminate the proxy process before stopping the container.
✅ **Manual verification**: 
- Started MCP server with defined port
- Verified proxy process was running
- Used `thv rm` …
> fix: ensure proxy processes are terminated when using thv rm

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/secrets/factory.go
This PR adds support for the `TOOLHIVE_SECRETS_PROVIDER` environment variable to allow overriding the secrets provider configuration without modifying the config file.
- **Added `ProviderEnvVar` constant** to `pkg/secrets/factory.go` for the environment variable name
- **Modified `GetProviderType()`** in `pkg/config/config.go` to check environment variable first, then fallback to config file
- **Environment variable takes precedence** over configuration file setting
- **Added comprehensive test coverage** for environment variable functionality
- **Maintains backward compatibility** with existing configuration approach
Users can now set the secrets provider using:
```bash
export TOOLHIVE_SECRETS_PROVIDER=encrypted
export TOOLHIVE_SECRETS_PROVIDER=1password
```
This will override any …
> feat: add TOOLHIVE_SECRETS_PROVIDER environment variable support

- cmd/thv/app/proxy.go
- docs/cli/thv_proxy.md
- pkg/auth/oauth/flow.go
- pkg/auth/oauth/oidc.go
- pkg/auth/oauth/oidc_test.go
Adds a new `--remote-auth-callback-port` flag to the `thv proxy` command that allows users to specify a custom port for the OAuth callback server during remote authentication. The flag defaults to port 8666.
- **Added `--remote-auth-callback-port` flag** to `thv proxy` command with default value 8666
- **Extended OAuth Config struct** with `CallbackPort` field for better configuration management
- **Updated `CreateOAuthConfigFromOIDC`** function to accept and pass through callback port parameter
- **Modified `NewFlow`** to use the specified callback port from config instead of auto-selecting
- **Updated all test functions** to handle the new callback port parameter
- **Maintained backward compatibility** with existing OAuth flows
- **Network Configuration Control**: Users can specify a …
> feat: add --remote-auth-callback-port flag to thv proxy

- cmd/thv/app/proxy.go
- pkg/auth/oauth/flow.go
The proxy should send the ID token (if available) instead of the access token.
With some providers (like Google), the access token is an opaque token and not the JWT like it is with Keycloak.
Fixes the proxy-to-mcp-server auth flow for Google and other IdPs.
> Update proxy to send the ID token

- pkg/healthcheck/healthcheck.go
- pkg/healthcheck/healthcheck_test.go
- pkg/transport/proxy/httpsse/http_proxy.go
- pkg/transport/proxy/httpsse/pinger.go
- pkg/transport/proxy/transparent/pinger.go
- pkg/transport/proxy/transparent/transparent_proxy.go
This PR implements a common healthcheck format for ToolHive proxy runners as requested in issue #162. Previously, the HTTP SSE proxy had a healthcheck endpoint while the transparent proxy did not, and they returned different formats.
- **New `pkg/healthcheck` package**: Provides standardized JSON response format with MCP server status
- **Common interface**: `MCPPinger` interface allows transport-specific ping implementations
- **Version integration**: Uses existing `pkg/versions` package for ToolHive version info
- **HTTP SSE Proxy**: Direct MCP ping through existing message channel using JSON-RPC
- **Transparent Proxy**: HTTP health check approach for SSE transport servers (avoids SSE session complexity)
- Added missing `/health` endpoint to transparent proxy
- Both proxies now return …
> feat: implement common healthcheck format for proxy runners

- docs/proposals/otel-integration-proposal.md
This proposal outlines a comprehensive approach to add OpenTelemetry observability to ToolHive's MCP server proxies through middleware-based instrumentation.
- Leverages existing middleware system for clean integration
- Supports both SSE and stdio transport modes
- Provides traces, metrics, and structured logging
- Includes MCP-specific instrumentation beyond HTTP metrics
- Supports multiple OTEL backends and Prometheus integration
- Maintains backward compatibility with zero performance regression
- Detailed technical design with implementation phases
- Configuration options and CLI integration
- Data model examples for traces and metrics
- Concrete example of tools/call instrumentation
- Prometheus integration pathways
- Security considerations and production readiness
The design …
> feat: Add OpenTelemetry integration design proposal

- .github/workflows/update-docs-website.yml
Adds a GitHub Actions workflow to send a repository_dispatch event to the docs-website repo when a new release is published.
Currently, it will only trigger on a CLI release (tag starting with "v") and not on operator releases, since the docs update workflow only refreshes CLI and API references at present.
Tested locally using [`act`](https://nektosact.com/introduction.html) to verify functionality.
Closes #656
Closes stacklok/docs-website#1
> chore: add workflow to trigger docs update

- examples/operator/mcp-servers/mcpserver_github.yaml
This PR updates the GitHub example for the Operator to use `podTemplateSpec` to inject the secret instead of using the `secrets` property.
Currently, the `secrets` struct in the MCPServer CRD does not function, users get an error (see #521):
```
Error: failed to get secrets: secret not found: github-token/token (none provider doesn't store secrets)
```
While we work on a permanent solution to secrets handling in K8s, injecting secrets via `podTemplateSpec` works.
> Fix the Operator example for GitHub

- cmd/thv/app/proxy.go
- pkg/auth/oauth/flow.go
- test/e2e/oidc_mock.go
- test/e2e/proxy_oauth_test.go
Use the functionality of token source:
https://pkg.go.dev/golang.org/x/oauth2@v0.30.0#Config.TokenSource
that allows to automatically refresh tokens when expired
Closes: #707
> feat: allow for tokens to expire/refresh

- .github/workflows/image-build-and-publish.yml
- .goreleaser.yaml
- pkg/updates/client.go
- pkg/versions/version.go
The following PR adds an explicit BuildType variable (defaults to `development`, set during official releases to `release`) which removes the need to set an explicit env var for when we want to indicate that this is a development build.
> Add an explicit BuildType build variable

- cmd/thv/app/rm.go
- pkg/api/v1/workloads.go
- pkg/workloads/manager.go
This copies the same behaviour added recently for stop. This change also fixes a bug where the deletion operation did not clean up the ingress/egress containers.
While looking at the runtime code, I discovered that the runtime does a force delete of containers, so there is no need to explicitly stop the container before force deleting.
> Make workload deletion asynchronous

- pkg/registry/data/registry.json
Updates two MCPs from the Anthropic reference servers (now deprecated) to their official repositories: Redis and Perplexity. Their image references are unchanged, just the repo.
Also refreshed their env vars and tool lists.
Note I marked the REDIS_HOST as required because the default "127.0.0.1" won't work when the MCP is containerized.
Closes #754
Ref #747
> Update Redis and Perplexity MCPs

- pkg/registry/data/registry.json
Adds the official [MongoDB MCP server](https://github.com/mongodb-js/mongodb-mcp-server) to the registry.
Tested using my MongoDB Atlas instance.
Closes #752
> Add the MongoDB MCP to the registry

- pkg/container/docker/client.go
- pkg/container/docker/squid.go
- pkg/container/kubernetes/client.go
Also de-dupe the logic between egress and ingress. The existing code had two separate functions which were nearly identical.
Note that this is a first step in a series of changes I plan to make. The eventual end goal is to make the runtime interface purely container and image based, and move workload operations into a separate interface.
> Move squid code into its own file

- pkg/container/docker/client.go
As part of the network isolation changes, an assumption was introduced that all MCP servers have an exposed port. This is not the case for stdio - the proxy runner attaches to a stdio MCP server via the container's stdin/stdout. When the new code was run with a stdio container, the MCP container would run, the proxy runner process would die, and the following error would appear in the logs - `Error: failed to set up transport: failed to create container: no exposed ports specified in options.ExposedPorts`.
This PR changes the logic to skip parsing the exposed ports when the transport type is stdio.
> Fix `no exposed ports specified in options.ExposedPorts` bug

- cmd/thv/app/version.go
- pkg/updates/checker.go
The following PR reduces the clutter from the version checks.
> Mute the version check output

- cmd/thv/main.go
- pkg/client/migration.go
- pkg/config/config.go
Migrates the old `auto_discovery` config flag to the new registration setup.
This includes:
- On application startup, check if the user has the old config flag active
- If config flag was set to True, perform the migration:
- Automatically registers all installed clients
- Sets the flag to false
- Notifies the user
- If config flag was set to False, do nothing
By adding this check on the `cmd/thv/main.go` we can guarantee this is always executed before any user can be affected, including API usage.
> Migrate old auto_discovery to new client registration setup

- pkg/client/config.go
- pkg/client/manager.go
note: This is for the API only. The CLI has the same issue, but the code there is duplicated. Rather than changing the code in multiple places, I'll create a followup PR to refactor the CLI implementation.
Ref #841
This creates the appropriate client configuration file if it doesn't exist, before attempting to write to it.
> Create client config file before writing to it

- pkg/client/config.go
As per Dan's feedback, we should use "streamable-http" not "http"
> Fix Streamable HTTP for Roo Code

- pkg/api/v1/workloads.go
This was ommitted from the API code. Need to figure out if this logic can be moved inside the runconfig creation code.
> Fix default permission profile for API

- .github/workflows/update-docs-website.yml
The update script in the docs repo now handles operator releases (currently, to refresh the CRD reference if updated), so this removes the release tag conditional on the triggering run.
> Trigger remote docs workflow on operator releases

- cmd/thv/app/commands.go
- cmd/thv/app/mcp.go
- docs/cli/thv.md
- docs/cli/thv_mcp.md
- docs/cli/thv_mcp_list.md
- docs/cli/thv_mcp_list_prompts.md
- docs/cli/thv_mcp_list_resources.md
- docs/cli/thv_mcp_list_tools.md
Note: Originally opened by Ozz.
- Add new 'thv mcp' subcommand for debugging MCP servers
- Support listing tools, resources, and prompts from MCP servers
- Provide both JSON and text output formats
- Include timeout and server URL configuration options
- Use mcp-go library for MCP protocol communication
- Add proper error handling for unsupported capabilities
- Follow existing code patterns and pass all linting checks
This enables developers to easily inspect MCP server capabilities for debugging and development purposes.
> feat: add MCP debug commands for listing tools, resources, and prompts

- cmd/thv-operator/api/v1alpha1/mcpserver_types.go
- cmd/thv-operator/controllers/mcpserver_controller.go
- cmd/thv-operator/controllers/mcpserver_oidc_test.go
- deploy/charts/operator-crds/Chart.yaml
- deploy/charts/operator-crds/README.md
- deploy/charts/operator-crds/templates/toolhive.stacklok.dev_mcpservers.yaml
- docs/operator/crd-api.md
Since the functionality on the thv side is not (and will not) be
implemented, let's deprecate the fields from the CRDs before removing
them in a subsequent release.
> Deprecate the serviceAccount/ClientID parameters from the CRDs

- cmd/thv/app/inspector.go
- pkg/container/docker/client.go
- pkg/transport/http.go
The logic for assigning a random port on the host was done at transport level, which was causing k8s to fail. Instead, move it to docker itself, so we continue with the regular logic in k8s
Closes: #902
> fix: only assign a random host port for docker

- pkg/registry/data/registry.json
The current `mcp/fetch` MCP server is slow to start and finish and isn't that secure of an image. We replace the one in our registry with the a Golang version called: [`gofetch`](https://github.com/StacklokLabs/gofetch) as it also provides provenance information that we can verify. More comparisons can be found [here](https://github.com/StacklokLabs/gofetch?tab=readme-ov-file#why-this-fetch-and-not-mcpfetch).
> feat: replaces `mcp/fetch` with `stackloklabs/gofetch`

- pkg/transport/http.go
There was a regression introduced this [commit](https://github.com/stacklok/toolhive/commit/106ea358c15c94db0841d8c2537ca6c1dead34bc#diff-38fecb0789c3417dfc50bf25d6986584a8821f57fc4ff0474c1f2ad4123fb3a0) that returned a default `0` value from the Kubernetes container runtime. This 0 value then gets returned to [exposedPort](https://github.com/stacklok/toolhive/blob/main/pkg/transport/http.go#L156) which is then is used to [override the targetport](https://github.com/stacklok/toolhive/blob/main/pkg/transport/http.go#L184), later suffering from the ["targetPort not set error"](https://github.com/stacklok/toolhive/blob/main/pkg/transport/http.go#L214) because the targetPort is set to `0`.
This (hacky) fix introduces a change that only overrides the targetPort with the exposed port if it is …
> fix: only override `targetPort` for docker runtime

- cmd/thv/app/common.go
- cmd/thv/app/logs.go
- cmd/thv/app/restart.go
- cmd/thv/app/rm.go
- cmd/thv/app/stop.go
This PR implements auto-completion functionality for the `thv` CLI using Cobra's completion features. Users can now use tab completion when typing MCP server names for commands that operate on containers, significantly improving the CLI user experience.
- **Added `completeMCPServerNames` function**: Provides auto-completion for MCP server names by querying the workloads manager to get currently managed MCP servers
- **Added `completeLogsArgs` function**: Specialized completion for the logs command that includes both server names and the special "prune" option
- **Enhanced commands with `ValidArgsFunction`**:
- `thv rm [container-name]` - completes with available MCP server names
- `thv stop [container-name]` - completes with available MCP server names
- `thv restart [container-name]` - …
> Add Cobra auto-completion for MCP server names

- pkg/registry/data/registry.json
Adds three official AWS MCP servers to the registry:
- [AWS Cost Analysis](https://github.com/awslabs/mcp/blob/main/src/cost-analysis-mcp-server)
- [AWS Diagram](https://github.com/awslabs/mcp/tree/main/src/aws-diagram-mcp-server)
- [AWS Documentation](https://github.com/awslabs/mcp/blob/main/src/aws-documentation-mcp-server)
Closes #866
> Add AWS docs, diagrams, and cost analysis MCPs

- cmd/thv/app/run.go
- cmd/thv/main.go
- pkg/container/docker/client.go
- pkg/container/factory.go
- pkg/container/images/docker.go
- pkg/container/images/image.go
- pkg/container/images/keychain.go
- pkg/container/images/registry.go
- pkg/container/runtime/types.go
- pkg/container/verifier/attestations.go
- pkg/container/verifier/sigstore.go
- pkg/container/verifier/utils.go
- pkg/container/verifier/verifier.go
- pkg/transport/http.go
* Implements a new `RegistryImageManager` based on `go-containerregistry`
* Adds authentication support for both image lookup and pull
* Adds authentication support for the provenance verification features
* Keeps backwards compatibility with the DefaultKeychain (local docker config for example). The flow is we'll look for potential credentials stored as env vars, if nothing is set we'll default to looking for credentials in the docker config file.
* Defaults to noop for k8s case
* Replaces the existing DockerImageManager
* **Continues to use the docker client for building the image in case of schema-based MCP servers** (needed because `go-containerregistry` does not support building images from Dockerfiles)
**What's left:**
**Tests done:**
Fixes: #926
> Add support for private OCI registries

- pkg/container/images/registry.go
The following PR fixes an issue where the daemon library was failing because it was expecting to find the local docker socket at the `/var/run/docker.sock`
> Pass the docker client connection to daemon

- pkg/api/v1/workloads.go
The condition was probably reversed, meaning that any explicitly set
PermissionProfile requests would be set to the default.
> Don't override non-nil PermissionsProfile

- pkg/api/server.go
- pkg/operator/telemetry/telemetry.go
- pkg/updates/client.go
- pkg/updates/client_test.go
Implements the new User Agent sent to the update service. The new User Agent now has the following format:
`toolhive/[component] [vXX] [release/local_build] ([operating_system])`
This PR includes the logic to obtain the component (CLI, API, operator, Toolhive UI), gets the version, adds the release/local_build flag based on the BuildType, and gets some base OS information.
> Implement the new User Agent sent to the update service

- pkg/container/docker/client.go
Fix #1080 
When ToolHive restarts a workload it checks if the container already exists and can be reused. If it cannot be reused, it deletes it and creates a new container.
This happens for every container in the workload, including egress and dns containers that are created when network isolation is enabled.
The code previously recreated the egress and dns containers, and then proceeded to remove them when recreating the core MCP server container, because it was removing all associated workloads.
With this update, it only deletes the container that it's about to recreate and leaves the associated containers, assuming they've already updated themselves.
This is a similar issue to what we saw earlier with the network being deleted.
> Prevent deleting proxy containers on restart

- cmd/thv/app/client_test.go
- pkg/runner/config_test.go
These are causing race conditions since they execute in parallel and need to set an environment variable in order to work.
Another issue I found: Now that we enforce that the proxy port is not already used, tests would fail locally when the sample port of 8080 was already in used.
Regarding the config env var race condition - In future, we may move the config to a database file, and we should address the lack of parameterization of the path at that point in time.
> Run client config CLI tests sequentially

- pkg/client/config.go
Release 1.102 of VS Code expects MCP configuration to be defined in an `mcp.json` file instead of the `settings.json` file. Change the configuration code to use this new file instead.
As part of this change, we debated whether we should support the old path as well. We decided not to since:
1) VS Code pushes updates aggressively, so we do not think that old
versions will remain in use long term.
2) MCP support in the older releases was in a "preview" mode, so it was
not intended to be stable long term.
> Use new MCP config path for VS Code 1.102 and later

- pkg/registry/data/registry.json
The following PR adds the https://github.com/googleapis/genai-toolbox MCP server. Note that it expects to get a CLI args with a mounted config file (tools.yaml) which defines its list of tools and the rest of its behaviour.
> Add genai-toolbox to the MCP registry

- test/e2e/run_tests.sh
This PR adds automatic detection of GitHub Actions environment and enables the `--github-output` flag for ginkgo when running e2e tests in GitHub Workflows.
- Modified `test/e2e/run_tests.sh` to check for `GITHUB_ACTIONS` environment variable
- When detected, automatically adds `--github-output` flag to ginkgo command
- Maintains backward compatibility for local runs
- Added user feedback message when GitHub Actions is detected
- Better integration with GitHub Actions workflow reporting
- Automatic detection without manual configuration
- No impact on local development workflow
> Add --github-output flag to e2e tests when running in GitHub Actions

- cmd/thv-operator/controllers/mcpserver_controller.go
- deploy/charts/operator/Chart.yaml
- deploy/charts/operator/README.md
- deploy/charts/operator/values.yaml
- renovate.json
The OCD in me wanted to rename it from toolhiveRunnerImage to proxyRunnerImage, but that would have been more work and required an operator release and chart dance.
> feat: migrates toolhive operator chart to use proxyrunner image

- pkg/mcp/tool_filter.go
- pkg/mcp/tool_filter_test.go
Tool filtering for SSE transport was not adding back the stripped `data:` prefix, breaking client parsing.
Basically it was sending
```
event: message
{"foo": "bar"}
```
Instead of
```
event: message
data: {"foo": "bar"}
```
> Fix tool filtering for SSE missing `data:` prefix.

- cmd/thv/app/run.go
- pkg/workloads/manager.go
Run the process in a go routine so it can be canceled properly. Also add removal of workloads when process is stopped
Closes: #1146
> feat: properly manage interrupt signal on foreground process

- pkg/container/runtime/types.go
- pkg/workloads/file_status.go
- pkg/workloads/file_status_test.go
- pkg/workloads/manager.go
- pkg/workloads/status.go
- pkg/workloads/status_test.go
- pkg/workloads/types.go
This moves the Get/List workload operations to the status manager interface. This is needed because the status manager implementation dictates which workloads can be found, and what their statuses should be.
The runtimeStatusManager implementation now relies on the runtime to provide details of which workloads are available, and their state. The fileStatusManager uses the status files, but also delegates to the runtime in order to handle workloads created before the status files were created.
Unit tests are added for workloads/status.go
Note that this does not wire in the file-based status tracking. That will be introduced in the next PR.
> Move GetWorkload/ListWorkload to status manager interface

- pkg/registry/data/registry.json
Adds Crystal DBA's Postgres MCP Pro server to the registry.
https://github.com/crystaldba/postgres-mcp
https://www.crystaldba.ai/blog/post/announcing-postgres-mcp-server-pro
Tested with a local PostgreSQL instance.
Closes #826 
> Add postgres-mcp-pro to registry

- cmd/thv/app/commands.go
- pkg/api/server.go
- pkg/operator/telemetry/telemetry.go
- pkg/operator/telemetry/telemetry_test.go
- pkg/updates/checker.go
- pkg/updates/checker_test.go
- pkg/updates/client.go
Adds a new mechanism to avoid checking for updates when running Toolhive in CI environments.
Also increases the frequency of checking for update from 4 hours to 30 minutes.
> Avoid checking for updates on CI environments and increase check frequency

- pkg/registry/data/registry.json
- Renamed to crowdstrike-falcon
- Explicitly set transport
- Adds network permission profile
> Update Falcon MCP to http and add network profile

- .github/workflows/update-registry.yml
- cmd/regup/app/update.go
* Updates the `regup update` command with `--verify-provenance` flag
* Updates the daily registry refresh job to verify if the MCP servers with provenance information continue to match it
* Removes any MCP servers that have provenance information configured but fail to match it during validation.
> Ensure MCP servers from the registry match their expected provenance information

- cmd/thv/app/build.go
- docs/cli/thv_build.md
- pkg/runner/protocol.go
This PR adds two new flags to the `thv build` command to allow generating Dockerfiles without building containers:
- `--dry-run`: Generates the Dockerfile and outputs it to stdout without building
- `-o, --output <file>`: Writes the generated Dockerfile to a specified file
These flags can be used together or separately. When both are used, the Dockerfile is written to the file without building.
- Added `Output` and `DryRun` fields to `BuildFlags` struct
- Modified `BuildFromProtocolSchemeWithName` to accept a `dryRun` parameter
- Updated `buildCmdFunc` to handle the new flags appropriately
- Fixed linting issues (file permissions, line length)
Tested the following scenarios:
- `thv build --dry-run uvx://mcp-server-git` - outputs Dockerfile to stdout
- `thv build -o /tmp/test.Dockerfile …
> Add --dry-run and -o flags to thv build command

- cmd/thv-operator/Taskfile.yml
You can now push images to OCP with e.g.:
```
task ocp-build-and-push
```
or add additional variable in case your cluster doesn't have proper certificates set up:
```
task ocp-build-and-push OCP_INSECURE_REGISTRY=true
```
There is a convenience target for verifying the images in-cluster called `ocp-verify-push`.
> Add several task targets to push images into OCP ImageStreams

- cmd/thv-operator/Taskfile.yml
This target enables deployment of the operator on OpenShift provided that the images have been pushed to the internal registry earlier.
> Add a task target to deploy operator from OCP internal registry

- pkg/runner/env.go
**Use case for this feature**
We want to enable a "no args" experience when using MCP servers locally, where `thv run {{server_name}}` will result in a successful start of the server with no additional flags/arguments needs. A gap in the functionality required to accomplish this is the inability to specify a default behavior for secret environment variables. Within a custom registry, default values may be specified for non-secret environment variables within the `ImageMetadata` for each server. There is no similar functionality for secret environment variables.
This PR addresses this gap by finding required secret environment variables values in the secrets manager. I think this solution is imperfect, and maybe should be optional. I have created this PR to get feedback on the feature gap …
> Auto-load required secrets from secrets manager, if they exist

- pkg/registry/data/registry.json
This PR adds 10 new MCP servers from the uncommitted registry to the main registry in alphabetical order:
- **arxiv-mcp-server**: AI assistant for searching and accessing arXiv research papers through MCP protocol
- **brightdata-mcp**: Web scraping and data extraction interface to Bright Data toolset with browser automation
- **ida-pro-mcp**: IDA Pro reverse engineering and analysis server for security research
- **magic-mcp**: AI-powered UI component generator by 21st.dev for React components
- **mcp-jetbrains**: MCP proxy for redirecting requests to JetBrains IDEs (Official tier)
- **mcp-neo4j-aura-manager**: Neo4j Aura cloud instance management and services
- **mcp-neo4j-cypher**: Cypher query execution against Neo4j databases with natural language interface
- **mcp-neo4j-memory**: …
> Add 10 new MCP servers to registry

- pkg/container/verifier/verifier.go
Sorry for creating this PR directly without an issue first - it's such a small formatting fix that I felt an issue would be overkill.
This changes `logger.Info` to `logger.Infof` for the bundle verification error in the verifier, since the message uses `%v` formatting and to remain consistent with the rest of the repository.
> Use Infof for formatted logging message

- pkg/registry/data/registry.json
IT was pointing to the wrong one and thus failing pulling
> Fix mcp-server-box container image tag

- pkg/workloads/manager.go
There were a number of places where a workload start could fail, and not set the status of the workload to error. This identifies and fixes those issues.
This change increased the cyclomatic complexity of the restart method beyond our limit, so I refactored the function to simplify it.
> Ensure that failed starts/restarts are cleaned up properly

- pkg/registry/data/registry.json
- Bump to 0.11.0
- Refresh tools list and add new relevant tags
- Corrected the GitHub Enterprise env var name
- Add optional env vars for toolsets, dynamic tool discovery, and read-only mode
The env vars are easier to discover and set than using the CLI args because they'll show up in the `thv registry info` output and in the UI.
> Update GitHub configuration and toolsets

- docs/registry/schema.json
> Allow two-character tags in registry schema

- pkg/registry/data/registry.json
This PR adds the dolt MCP server to the registry, providing Git-like version control for SQL databases.
- Added dolt MCP server configuration to registry.json
- Positioned alphabetically between crowdstrike-falcon and elasticsearch
- Includes comprehensive toolset for database operations:
- Database branching and merging capabilities
- Schema and data versioning
- Remote repository management
- Query and table operations
- **Transport**: streamable-http
- **Tier**: Official
- **Tools**: 41 comprehensive database and version control tools
- **Network permissions**: Configured for localhost and dolthub.com access
- **Environment variables**: Properly configured for database connection and MCP mode
https://github.com/dolthub/dolt-mcp
> Add dolt MCP server to registry

- cmd/thv/app/client.go
- pkg/api/v1/clients.go
- pkg/client/manager.go
- pkg/client/mocks/mock_manager.go
Move client listing logic into client manager so it can be reused.
> Return registered groups from API

- cmd/thv/app/run.go
This PR fixes an issue where running MCP servers with protocol schemes (like `npx://@scope/package`) would fail due to the raw protocol URL being used as the workload name, causing filesystem errors from invalid characters (colons and slashes).
When running:
```bash
thv run npx://@modelcontextprotocol/server-sequential-thinking
```
The command would fail with:
```
Error: failed to get workload: failed to acquire read lock for workload npx://@modelcontextprotocol/server-sequential-thinking: open /var/home/user/.local/share/toolhive/statuses/npx:/@modelcontextprotocol/server-sequential-thinking.lock: no such file or directory
```
The fix skips group validation for protocol schemes when no explicit name is provided, because:
1. The workload doesn't exist yet with the protocol URL as its name …
> Fix protocol scheme workload name validation issue

- pkg/migration/default_group.go
- pkg/migration/migration.go
This is to handle the UI and CLI using different thv versions. The CLI will now always check if any workloads or clients need to be migrated.
Also, only creates the default group if not present and silences some of the noisy logs.
> Continuously check if group migration is needed

- cmd/thv/app/mcp.go
- docs/cli/thv_mcp_list.md
- docs/cli/thv_mcp_list_prompts.md
- docs/cli/thv_mcp_list_resources.md
- docs/cli/thv_mcp_list_tools.md
This PR enhances the `thv mcp list` command to accept both server URLs and server names from running workloads via the `--server` flag.
- Modified `--server` flag to accept both URLs and server names from running workloads
- Added `resolveServerURL` function to look up running servers by name using the efficient `GetWorkload` method
- Improved error messages for better user experience
- Removed unnecessary logger calls that could corrupt JSON output
- Updated flag documentation to reflect the new functionality
This allows users to conveniently reference MCP servers by their friendly names instead of having to remember or look up their URLs, while maintaining backward compatibility with direct URL usage.
```bash
thv mcp list tools --server fetch
```
```bash
thv mcp list tools --server …
```
> feat: enhance thv mcp list to accept server names in addition to URLs

- .github/workflows/verify-docgen.yml
- cmd/help/verify.sh
The CI `verify-docgen` action was only checking the CLI documentation, this adds a check for the API documentation.
> Check that the API docs are up to date on CI

- deploy/charts/operator/Chart.yaml
- deploy/charts/operator/README.md
- deploy/charts/operator/README.md.gotmpl
Small update to include a reference on how to use a custom values file to install via helm chart. References the newly included values-openshift.yaml which has been bumped to include the latest released version of the operator 0.2.8.
Open question; for the custom values file, values-openshift.yaml in this case, how should it be referenced to be consistent with other README's and the docs?
./values-openshift.yaml (assuming it's in the current dir but being explicit)
values-openshift.yaml (also assuming it's in the current directory but implicit)
./deploy/charts/operator/values-openshift.yaml (assuming one has cloned the repo and is in the root of the project)
raw github ref?
Please feel free to update as required.
> Updated the operator deployment README with a custom example. Include 0.2.8.

- pkg/client/config.go
Cline fixed up their Streamable HTTP support back in v3.17.10; updating our config to match.
Tested with latest version of Cline using stdio, sse, and stramable-http servers.
> Update Cline client config

- .github/workflows/issue-triage.yml
We haven't given Claude any guidelines on how to assess priority and it lacks the context, meaning the priority labels assigned are incorrect.
> Remove priority label step from Claude triage

- pkg/registry/types.go
Fixes a nil pointer dereference panic that occurs when using protocol schemes like `npx://`, `uvx://`, or `go://`.
When using protocol schemes, the `retriever.GetMCPServer()` function returns a non-nil `ServerMetadata` interface that contains a nil underlying `ImageMetadata` pointer. This causes a segmentation fault when methods like `GetTransport()` are called on the nil receiver.
The issue occurs because:
1. Protocol schemes are processed and build Docker images dynamically
2. The `imageMetadata` variable remains `nil` in the protocol scheme branch
3. This `nil` pointer is returned as a `ServerMetadata` interface
4. In Go, a `nil` pointer cast to an interface is not `nil` - it's an interface with a `nil` underlying value
5. When `serverMetadata != nil` check passes but `GetTransport()` …
> Fix nil pointer dereference when using protocol schemes

- .github/workflows/update-registry.yml
the usage of `cd` was setting us in the wrong directory so we couldn't
overwrite the registry file.
> Use pushd instead of cd in update registry job

- pkg/container/factory.go
- pkg/container/kubernetes/client.go
- pkg/container/runtime/types.go
This PR fixes some inconsistencies in how we detect and select container runtimes. The main issue was that the auto-detection logic was a bit unpredictable and hard to override.
**Runtime detection order**: We now check Docker first, then Kubernetes. This makes more sense since Docker is more commonly available and faster to detect.
**Environment variable override**: Added `TOOLHIVE_RUNTIME` env var so users can explicitly choose their runtime without relying on auto-detection.
**Better Kubernetes availability checking**: Added a proper `IsAvailable()` method to the Kubernetes client that actually tries to connect (with a 5s timeout) instead of just checking environment variables.
**Cleaner code**: Simplified the factory auto-detection logic - it's now easier to follow and modify.
The old …
> Improve container runtime detection logic

- pkg/container/kubernetes/client.go
- pkg/container/kubernetes/client_test.go
When using `TOOLHIVE_RUNTIME=kubernetes thv list`, no MCP servers were shown even though `kubectl get mcpservers.toolhive.stacklok.dev` worked correctly. This happened because:
1. The `getCurrentNamespace()` function was falling back to "default" when running outside the cluster
2. The kubectl context was set to a non-default namespace  
3. The `ListWorkloads()` method was showing both main MCP server pods and proxy pods
- **Namespace Detection**: Enhanced `getCurrentNamespace()` to read from kubectl context when running outside cluster
- **Pod Filtering**: Updated label selector to only show main MCP server pods (StatefulSets) by requiring `toolhive-tool-type` label
- **All-Namespaces Support**: Added `TOOLHIVE_KUBERNETES_ALL_NAMESPACES` environment variable to list pods from all …
> Fix Kubernetes runtime list command and add all-namespaces support

- pkg/mcp/middleware.go
- pkg/mcp/tool_filter.go
- pkg/mcp/tool_filter_test.go
This change prepares the ground for the implementation of tool override by changing the way tool middlewares are configured.
As of now, tool middlewares accept a flat list of strings acting as a filter on the tools available to the Client. This is not sufficient once tool override is implemented, since we have to distinguish between a tool being filtered, being overridden, or both.
This is meant to be 100% backwards compatible, as the feature will be implemented in a follow-up PR.
> Refactor tool middlewares configuration mechanism.

- pkg/container/docker/squid.go
Ingress and egress proxy containers end up in a bootloop upon start in some cases.
I have faced this issue when setting up an MCP with network isolation like this:
```sh
thv run --name fetch1 --isolate-network --permission-profile ./fetch-profile.json fetch
```
<details>
<summary>fetch-profile.json</summary>
```json
{
"network": {
"outbound": {
"insecure_allow_all": false,
"allow_host": [
"httpbin.io"
],
"allow_port": [
443
]
}
}
}
```
</details>
Prepare the Squid config file as generated by Toolhive for the egress proxy container:
<details>
<summary>squid-original.conf</summary>
```text
http_port 3128
visible_hostname fetch1-egress
access_log stdio:/dev/stdout squid
pid_filename /tmp/squid.pid
cache deny all
cache_mem 0 MB
maximum_object_size 0 KB
maximum_object_size_in_memory 0 KB …
```
> Fix proxy memory allocation error

- docs/proposals/upstream-mcp-registry-format-support.md
- pkg/registry/upstream.go
- pkg/registry/upstream_conversion.go
- pkg/registry/upstream_conversion_test.go
ToolHive currently uses its own registry format, which creates barriers for ecosystem interoperability. The MCP community has developed a standardized \`server.json\` format that other tools use, but ToolHive cannot consume or produce this format.
This PR adds bidirectional conversion between ToolHive's registry format and the upstream MCP community format. This enables ToolHive to participate in the broader MCP ecosystem while preserving its advanced container-focused features.
- **\`pkg/registry/upstream.go\`**: Structs matching the upstream \`server.json\` schema
- **\`pkg/registry/upstream_conversion.go\`**: Conversion functions in both directions
- **\`pkg/registry/upstream_conversion_test.go\`**: Comprehensive test coverage
**Upstream → ToolHive:**
- \`docker\` packages → Direct …
> Add support for upstream MCP registry format

- cmd/thv-operator/controllers/mcpserver_controller.go
- cmd/thv-operator/controllers/mcpserver_resource_overrides_test.go
This PR implements the requirement to hardcode the operator to deploy the proxy runner with `TOOLHIVE_RUNTIME=kubernetes`.
- **Modified `ensureRequiredEnvVars` function**: Added logic to automatically set `TOOLHIVE_RUNTIME=kubernetes` environment variable for all proxy runner deployments created by the operator
- **Updated test expectations**: Modified test cases to include the new environment variable in expected results
- **Follows existing patterns**: Uses the same approach as other required environment variables like `HOME` and `XDG_CONFIG_HOME`
The operator now automatically adds the `TOOLHIVE_RUNTIME=kubernetes` environment variable to every proxy runner deployment it creates. This happens in the `ensureRequiredEnvVars` function during deployment creation. The environment variable …
> Hardcode TOOLHIVE_RUNTIME=kubernetes in operator proxy deployments

- pkg/transport/proxy/transparent/transparent_proxy.go
The routine `modifyForSessionId` in our implementation of transparent proxy uses `bufio.Scanner` to scan through the response bytes in search of the session id.
Said `bufio.Scanner` internally sets a maximum token size of 64kB which is easily exceeded by `plotting-mcp` which returns images. When such a threshold is reached, the scanner's `Scan` method returns `false` and sets the error to `ErrTooLong`
([here](https://github.com/golang/go/blob/release-branch.go1.25/src/bufio/scan.go#L200-L203), which our code ignored.
This change mitigates the issue by raising the maximum token size to 1MB and adds basic error handling at the end of the scan loop.
Fixes #1535
> Raise scanner max token size in transparent proxy.

- pkg/transport/proxy/httpsse/http_proxy.go
- pkg/transport/proxy/httpsse/http_proxy_integration_test.go
- pkg/transport/proxy/httpsse/http_proxy_integration_test.go.bak
- pkg/transport/proxy/httpsse/http_proxy_test.go
This PR fixes race conditions in the HTTP SSE proxy that were causing MCP clients to disconnect frequently.
**Related-to #1572**
The HTTPSSEProxy had race conditions where multiple goroutines could attempt to close the same channel simultaneously, causing panics. This happened when both the disconnect monitor and `sendSSEEvent` tried to handle a disconnected client at the same time.
1. **Added `removeClient()` method**: Centralized client cleanup logic with proper synchronization
2. **Added `closedClients` tracking map**: Prevents double-close attempts on channels
3. **Changed `sseClientsMutex` to `RWMutex`**: Better concurrency for read-heavy operations
4. **Modified `sendSSEEvent` synchronization**: Hold read lock during entire send operation to prevent channels from being closed …
> Fix race conditions and improve stability in HTTPSSEProxy

- cmd/thv/app/proxy_stdio.go
- pkg/process/detached.go
- pkg/process/pid.go
- pkg/runner/runner.go
- pkg/transport/proxy/manager.go
- test/e2e/osv_mcp_server_test.go
If not, the proxy pid file is not detected and workload is marked as unhealthy
Closes: #1587
> always write a pid file even if we run in foreground

- pkg/process/pid.go
- pkg/process/pid_test.go
This PR implements a fallback mechanism to maintain backward compatibility with existing deployments after PR #1604 changed the PID file location from `os.TempDir()` to XDG data directories.
PR #1604 introduced a breaking change by moving PID files from `/tmp/` to XDG data directories (typically `~/.local/share/toolhive/pids/`). This breaks existing deployments that still look for PID files in the old location.
This PR adds backward compatibility by:
1. **Reading**: First checking the new XDG location, then falling back to the old `/tmp/` location
2. **Writing**: Always writing to the new XDG location (for forward migration)
3. **Removing**: Cleaning up PID files from both locations to ensure proper cleanup during migration
- Added `getOldPIDFilePath()` helper to get the legacy PID file …
> Add backward compatibility for PID file location changes

- pkg/mcp/tool_filter.go
- pkg/mcp/tool_filter_test.go
- pkg/mcp/tool_middleware_test.go
This change makes use of the provided filter and override configuration in tool middlewares. Both middlewares now process `tools/call` and `tools/list` commands by checking both overrides and filtering, specifically:
* `tools/list` responses, which the proxy received from the real MCP server, must be modified to contain tools whose names might be overridden (as well as filtered)
* `tools/call` requests, which the proxy received from the Client, must be modified to refer to the original tool name
As a refresher for the reviewer, keep in mind that filtering is expressed in terms of tool names used by the client, so the user-visible (or client-visible) name must be determined before the lookup on the filter. This makes it so that
* `tools/list` must first look the override up and only then …
> Add tool name override to tool middleware.

- pkg/runner/middleware.go
If the authentication middleware would detect that the user is not
authenticated, we shouldn't event try to parse the request. So, this
optmizes a little.
> Move authentication middleware to run before tool-filtering

- pkg/runner/config.go
- pkg/runner/config_builder.go
- pkg/runner/config_test.go
- pkg/validation/validation.go
- pkg/workloads/types/validate.go
- pkg/workloads/types/validate_test.go
This PR improves the security posture of ToolHive by adding proper input sanitization for user-provided workload names. This hardening addresses CodeQL security scanner warnings about 'Uncontrolled data used in path expression'.
- **Added `SanitizeWorkloadName()` function** to `pkg/validation/validation.go`
- Ensures names only contain alphanumeric characters and dashes
- Returns both the sanitized name and a boolean indicating if modification occurred
- **Updated `WithContainerName()` in `pkg/runner/config.go`**
- Now uses the new validation function for consistent sanitization
- Returns a boolean indicating if the name was modified
- Applies sanitization to both container and remote server names
- **Updated `config_builder.go`**
- Warns users when their provided names are sanitized
- …
> Harden container name handling with input sanitization

- cmd/thv/app/run_flags_test.go
- pkg/api/v1/registry.go
- pkg/api/v1/registry_test.go
- pkg/client/config.go
- pkg/client/config_test.go
- pkg/client/discovery.go
- pkg/client/discovery_test.go
- pkg/client/migration.go
- pkg/config/interface.go
This PR enables parallel test execution by eliminating XDG environment variable manipulation that prevented tests from running concurrently in Go 1.24+.
- **Added `config.Provider` interface** for dependency injection of configuration operations
- **Implemented `ClientManager` struct** to encapsulate client operation dependencies
- **Created `DefaultProvider` and `PathProvider`** for backward compatibility and test isolation
- **Replaced `t.Setenv("XDG_CONFIG_HOME")` usage** with isolated config providers
- **Enabled `t.Parallel()` in all affected test files** for concurrent execution
- **Added comprehensive mock client configurations** to eliminate race conditions
- **Used `t.Cleanup()` instead of defer** for better test practices
- `cmd/thv/app/run_flags_test.go` - Fixed XDG usage, …
> Enable parallel test execution by eliminating XDG global state

- .github/workflows/test.yml
- Taskfile.yml
Summary
- Integrate gotestfmt for unit test output formatting
- Reduce verbosity by hiding successful tests/packages and empty packages
- Upload the raw /tmp/gotest.log as a workflow artifact for debugging
Details
- Taskfile: added gotestfmt-install task and updated the Linux/macOS unit test path to run `go test -json -v -race` piped to `gotestfmt -hide successful-tests,successful-packages,empty-packages`, while saving the unformatted log to /tmp/gotest.log
- GitHub Actions: Tests workflow now uploads /tmp/gotest.log as an artifact (always)
Notes
- This change touches only standard unit tests; coverage and e2e tasks remain unchanged
- gotestfmt v2 returns non-zero on failing tests by design; we use `set -euo pipefail` so CI correctly fails on test failures
- Platform filters in the …
> Format unit test output with gotestfmt and upload raw log

- pkg/api/v1/workloads.go
- pkg/runner/retriever/retriever.go
Hi @blkt,
I worked on the issue where API endpoints for creating and updating workloads returned HTTP 500 even when the error was due to invalid user input in the run config.
Please let me know if any adjustments are needed — happy to refine further 🙂
Thanks!
> solution for Workloads API return HTTP 500 on invalid config #1676

- pkg/workloads/statuses/file_status.go
- pkg/workloads/statuses/file_status_test.go
Previously, workload names with slashes would lead to when accessing status files or creating locks. Fix by swapping slashes for hyphens in file names.
Fixes: #1686
> Ensure slashes in workload names are handled by file status manager

- .github/workflows/test.yml
I put the token in the wrong place
> fixes where the `CODECOV_TOKEN` is used

- pkg/workloads/statuses/file_status.go
It is expected that some workloads wont have run configs. If we get an error, just debug log it and proceed as if the workload is not remote.
> Ignore errors if remote workload status cant be checked

- pkg/workloads/statuses/file_status.go
- pkg/workloads/statuses/file_status_test.go
- pkg/workloads/statuses/mocks/mock_status_manager.go
- pkg/workloads/statuses/status.go
This is part of a process of replacing the dedicated pid files with the status files. This is needed for k8s since we do not need PID files, and writing them creates problems.
This change does not alter how PID files are managed: it just provides the operations needed to add them to status files, and implements tests.
> Add methods to status manager for storing PIDs

- codecov.yaml
There are a bunch of folders and packages that we don't want codecov to report coverage (or lackthereof) on.
> adds exclusions for codecov

- pkg/transport/proxy/httpsse/http_proxy.go
- pkg/transport/proxy/httpsse/http_proxy_test.go
- pkg/transport/session/errors.go
- pkg/transport/session/manager.go
- pkg/transport/session/proxy_session.go
- pkg/transport/session/sse_session.go
Unified session management across all transport types by migrating
HTTPSSEProxy from direct map storage to use the centralized session
manager. Extended the session interface to support type differentiation
and metadata storage, enabling future support for distributed session
storage backends like Redis/Valkey.
Key changes:
- Added session types (MCP, SSE, Streamable) for better session handling
- Created SSESession type with SSE-specific functionality
- Migrated HTTPSSEProxy to use session manager with proper TTL
- Updated factory pattern to support different session types
- Fixed all tests to work with the new session management
- Maintained backward compatibility with existing code
> Refactor session management to support multiple storage backends

- pkg/authz/middleware.go
- pkg/transport/proxy/streamable/dispatcher.go
- pkg/transport/proxy/streamable/streamable_proxy.go
- pkg/transport/proxy/streamable/streamable_proxy_mcp_client_integration_test.go
- pkg/transport/proxy/streamable/streamable_proxy_spec_test.go
- pkg/transport/proxy/streamable/utils.go
- pkg/transport/session/streamable_session.go
- pkg/transport/stdio.go
Refactor the existing Streamable HTTP proxy to improve request/response correlation and add proper session management per MCP specification.
- **Composite ID Routing**: Implement sessID|idKey routing for reliable request/response correlation across concurrent clients
- **Response Dispatcher**: Extract response dispatching into dedicated dispatcher with waiter-based routing mechanism
- **Session Management**: Introduce proper session management with Manager and StreamableSession types for session lifecycle control
- Implement spec-compliant HTTP method handlers:
- GET returns 405 (SSE not offered on this endpoint)
- DELETE properly terminates sessions with 204
- POST handles single/batch requests and SSE streaming
- Fix session header handling with automatic Mcp-Session-Id assignment on …
> Enhance Streamable HTTP proxy with session management and ID routing

- cmd/thv/app/inspector.go
- cmd/thv/app/inspector/version.go
Fixes #997
This fixes multiple issues with the `thv inspector` command, mostly related to changes introduced with Inspector v0.14.1 and above:
1. Fixes the transport for stdio servers; ToolHive was using the underlying transport when building the Inspector URL instead of sse.
2. Added `HOST=0.0.0.0` env var to the Inspector container; v0.14.1 changed the inspector proxy's binding to 127.0.0.1, fixing the problem where the web interface could not connect through to the container.
3. Inspector also introduced an authentication token which is now required. Added code to generate this (so we know the value), inject it via the `MCP_PROXY_AUTH_TOKEN` env var, and then append it to the generated URL (following the default behavior where the token is generated at startup and printed on the …
> Fix connection and auth issues with Inspector

- .github/workflows/releaser-helm-charts.yml
- .github/workflows/releaser.yml
- .github/workflows/run-on-main-charts.yml
- .github/workflows/update-docs-website.yml
Changes the update-docs-website workflow to trigger explicitly as a reusable workflow instead of relying on the release event.
This addresses the issue of automatic PRs not being opened for Operator/CRD Helm chart releases since those are created via another workflow's GITHUB_TOKEN.
Fixes stacklok/docs-website#74
The previous attempt, #1477 failed and was reverted because the helm releaser needed `secrets: inherit` passed to it from its own parent (run-on-main-charts.yml), and because the chart-releaser-action output was not as expected. This revision fixes both.
Note for the helm releaser; since chart-releaser-action might process multiple Helm charts in one workflow, I had to build a JSON list of the releases to then matrix the docs update workflow call. It's ugly, but it works. …
> Fix update-docs-website workflow triggers

- go.mod
- pkg/container/docker/sdk/client_unix.go
- pkg/container/docker/sdk/factory.go
- pkg/container/runtime/types.go
I needed to add `colima` in order to use `thv` in my current setup. Opening as draft as I'm traveling as I write this PR and haven't given due diligence of going through the Dev Guide. Hoping to share for guidance.
Before:
```sh
bin/thv client setup                       
A new version of ToolHive is available: v0.2.5
Currently running: v8ef1a70-dirty
Error: failed to create client manager: no supported container runtime available: container runtime not found
```
After:
```sh
bin/thv client setup
A new version of ToolHive is available: v0.2.5
Currently running: v8ef1a70-dirty
Successfully registered client: vscode
Successfully registered client: cursor
10:02AM INF Creating new client config file at /Users/rhartje/Library/Application Support/Code/User/mcp.json
10:02AM INF Creating new …
```
> Support colima

- docs/cli/thv_run.md
- pkg/runner/runner.go
- pkg/workloads/manager.go
- pkg/workloads/manager_test.go
Whenever we write or delete pid files, also update the status files. At this point in time, we do not consume this field, we just populate it. This reduces the set of changes in upcoming PRs.
> Update PID field in status files

- .github/workflows/run-on-main-charts.yml
- .github/workflows/run-on-pr-charts.yml
both paths and paths-ignore aren't allowed and causes build failures. example https://github.com/stacklok/toolhive/actions/runs/17592909145
> removes path ignore as it only allows paths on its own

- CLAUDE.md
- cmd/thv/app/commands.go
- docs/cli/thv.md
- docs/proposals/thvignore.md
When this PR merges: https://github.com/stacklok/toolhive/pull/1332
I'd like to rebase on top of mine to include further changes to the documentation and tests.
> Colima Runtime Documentation Update

- cmd/thv/main.go
- pkg/container/factory.go
The following PR makes the no container runtime error message a bit better by doing the check early so it's not being wrapped up in a few other error messages. 
Before:
```
7:56PM  ERROR   Failed to perform default group migration: failed to initialize managers: failed to create workloads manager: no available runtime fou
nd
```
After:
```
1:49AM  ERROR   no container runtime available. ToolHive requires Docker, Podman, Colima, or a Kubernetes environment to run MCP servers
```
> Exit early if container runtime is not found

- pkg/container/docker/client.go
- pkg/container/docker/client_info_test.go
- pkg/container/docker/client_list_test.go
- pkg/container/docker/client_stop_test.go
- pkg/container/docker/mocks_test.go
Summary
Add a minimal adapter around the Docker SDK client and unit tests for key Docker runtime query paths. This enables fast, deterministic tests without requiring a running Docker daemon.
What changed
- Introduced a small docker client adapter in the Docker runtime client and routed list/inspect/stop through it.
- Added unit tests for listing workloads, inspecting workloads (including port parsing and created time fallback), checking running status, and stopping workloads.
- Centralized a small test fake for the adapter in mocks_test.go.
Motivation
Increase test coverage for logic-heavy query paths and make them easier to evolve safely.
Validation
- task lint-fix: 0 issues
- go test ./pkg/container/docker: ok
- golangci-lint (package scope): 0 issues
> Add adapter and unit tests for Docker query paths

- pkg/operator/accessors/mcpserver_accessor.go
- pkg/operator/accessors/mcpserver_accessor_test.go
The ToolHive Operator controller files are getting quite large now and there seems to be some duplication appearing. In this PR we add a simple addition by creating a new `accessors` package in `pkg/operator` that is responsible for getting specific fields on the `MCPServer` spec and performing nil checks in the right places. 
This allows for:
- Reduces code in the operator controller files
- Allows for more granular tests
- Allows for reuse
This somewhat opens the door for future helper interfaces/functions that allow for more granular testing ensuring we adhere to DRY without it all being among thousands of lines of code of certain controller files. Some of the operator code is at a point now where it needs to be refactored and split out. This is the start of some of that effort
> Refactors Accessor Logic for `MCPServer` Fields Into Specific Package

- pkg/container/docker/client.go
- pkg/container/docker/client_create_test.go
- pkg/container/docker/client_deploy_test.go
- pkg/container/docker/mocks_test.go
- Add unit tests for DeployWorkload (stdio/sse isolation, no-isolation, unsupported transport)
- Add unit tests for createMcpContainer (isolated/non-isolated, invalid port specs, no DNS)
- Add unit tests for createContainer (new, reuse-if-stopped, mismatch remove+recreate; error propagation)
- Extend dockerAPI with ContainerCreate/Start/Remove to enable hermetic tests
- All tests pass (go test ./pkg/container/docker -v)
> Add Docker workload creation unit tests; extend dockerAPI seam

- cmd/thv-operator/controllers/mcpserver_controller.go
- cmd/thv-operator/controllers/mcpserver_runconfig.go
- cmd/thv-operator/controllers/mcpserver_runconfig_test.go
Replace hardcoded "authz.json" with the existing package-level constant defaultAuthzKey in the operator controllers to centralize the default and avoid drift.
What/Why:
- Centralize the default authorization filename into a single constant used across controller code paths.
- Prevent future divergence and make updates easier.
Changes:
- Use defaultAuthzKey when deriving the ConfigMap key fallback.
- Use defaultAuthzKey for volume items (key/path) for both ConfigMap and inline authz.
- Build the --authz-config flag path using defaultAuthzKey instead of a literal.
- Remove the redundant test-local constant so tests rely on the shared package constant.
Validation:
- Operator unit tests pass locally.
> operator: use defaultAuthzKey for authz filename

- .github/workflows/e2e-tests.yml
- test/e2e/audit_middleware_e2e_test.go
- test/e2e/client_test.go
- test/e2e/fetch_mcp_server_test.go
- test/e2e/group_list_e2e_test.go
- test/e2e/group_rm_test.go
- test/e2e/group_test.go
- test/e2e/inspector_test.go
- test/e2e/list_group_e2e_test.go
- test/e2e/osv_authz_test.go
- test/e2e/osv_mcp_server_test.go
- test/e2e/osv_streamable_http_mcp_server_test.go
- test/e2e/protocol_builds_e2e_test.go
- test/e2e/proxy_oauth_test.go
- test/e2e/proxy_stdio_test.go
- test/e2e/proxy_tunnel_e2e_test.go
- test/e2e/restart_test.go
- test/e2e/rm_group_test.go
- test/e2e/run_tests.bat
- test/e2e/run_tests.sh
- test/e2e/stdio_proxy_over_streamable_http_mcp_server_test.go
- test/e2e/telemetry_middleware_e2e_test.go
- test/e2e/thvignore_test.go
- test/e2e/unhealthy_workload_test.go
This PR improves E2E test organization and CI execution.
What changed
- Added Ginkgo labels to all test/e2e suites to classify tests into broad categories:
- core – CLI, groups, listings, restart, thvignore
- mcp – server bring-up and protocol coverage (SSE, streamable-http, protocol builds, inspector)
- proxy | middleware | stability – proxy oauth/stdio/tunnel, audit middleware, telemetry middleware, unhealthy detection
- Updated E2E runners to support label-driven subsets:
- test/e2e/run_tests.sh and test/e2e/run_tests.bat accept LABEL_FILTER (or E2E_LABEL_FILTER) and pass --label-filter to Ginkgo
- Split the E2E workflow into a 3-entry matrix running in parallel:
- core → LABEL_FILTER=core
- mcp → LABEL_FILTER=mcp
- proxy/middleware/stability → LABEL_FILTER='proxy || middleware || …
> Split e2e tests via labels

- pkg/config/config.go
Merged before e2e test failures were understood.
This reverts commit 766f6085f60a7db3a570ab5aa0299eff0fc39e8f.
> Revert "Force reload of config singleton after writing config changes… (#1923)"

- cmd/thv-operator/README.md
- cmd/thv-operator/Taskfile.yml
- Added clear instructions for running Operator E2E and unit/integration tests in README
- Clarified that all operator task commands should be run from the project root
- Updated Taskfile to auto-install Chainsaw for local runs, skipping in CI
Ref: #1843
> docs(operator): add E2E test instructions, clarify task usage, and automate Chainsaw install

- cmd/thv/app/commands.go
- cmd/thv/main.go
- Exempt informational commands (`version`, `search`, `registry`, `mcp`) from container runtime availability checks
- Skip migrations for informational commands to prevent unnecessary error messages
- Non-operational commands can now run without a runtime being installed
> Allow informational commands to run without container runtime

- test/e2e/fetch_mcp_server_test.go
Implements missing E2E test coverage for the `--tools-override` CLI flag as requested in GitHub issue #1515.
The tests will automatically run in CI under the "mcp" label filter, ensuring they're included in the existing test pipeline.
Closes #1515
> Add E2E tests for tool override functionality

- deploy/keycloak/setup-realm.sh
Extends the keycloak setup script we have with settings to perform a token exchange of tokens with aud=mcp-servers for tokens with aud=backend. To test:
```
TOKEN=$(curl -s -d "client_id=mcp-test-client" -d "client_secret=mcp-test-client-secret" -d "username=toolhive-user" -d "password=user123" -d "grant_type=password" "http://localhost:8080/realms/toolhive/protocol/openid-connect/token" | jq -r '.access_token')
curl -s -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
-d "client_id=mcp-server" \
-d "client_secret=PLOs4j6ti521kb5ZVVwi5GWi9eDYTwq" \
-d "subject_token=$TOKEN" \
-d "subject_token_type=urn:ietf:params:oauth:token-type:access_token" \
-d "scope=backend-access" \
"http://localhost:8080/realms/toolhive/protocol/openid-connect/token"
```
Which gives you a token …
> Enable token exchange for the example KC clients

- docs/proposals/upstream-mcp-registry-format-support.md
This PR adds a proposal for integrating the upstream MCP Registry (server.json) with ToolHive’s run flow.
Overview
- Keep `thv run` inputs unchanged (by name, image, protocol, remote URL)
- Resolve names via the configured registry; when upstream (URL) registry is configured, fetch server.json and convert to ToolHive metadata
- Initial package types supported: oci (direct image), npm (npx://), pypi (uvx://)
- Minimal code change: in the registry path, detect protocol strings produced by conversion and synthesize images via the existing protocol builder (IsImageProtocolScheme + HandleProtocolScheme) before verification/pull
- Align internal upstream model/converter to official schema fields (registry_type, identifier, version, transport)
- No changes to builder/runner/middleware; other …
> Add proposal: Upstream MCP Registry (server.json) integration for ToolHive run flow

- cmd/thv/app/inspector.go
- pkg/labels/labels.go
- pkg/migration/default_group.go
- pkg/workloads/manager.go
We were seeing some warnings about migration processes, errors checking proxy, etc... on inspector
But this was caused because those processes didn't need to run for auxiliary workloads. So add a check to prevent this
Closes: #1696
> do not execute migration or proxy checks for auxiliary workloads

- renovate.json
Renovate was proposing minor version updates for kindest/node (e.g., 1.31.9 → 1.34.0) instead of only patch updates as intended.
The package rules for kindest/node were missing the `matchManagers` specification for `custom.regex`. Since kindest/node is detected by a custom regex manager (defined in the customManagers section), the rules need to explicitly match that manager.
- Added `matchManagers: ["custom.regex"]` to both kindest/node package rules
- Changed `excludePackageNames` to `matchPackageNames` with negation pattern for consistency with Renovate's preferred syntax
- Minor and major updates for kindest/node are now disabled (only patch updates allowed)
- Patch updates are grouped together
- The dockerfile template base images rule excludes kindest/node to avoid conflicts …
> Fix renovate config to restrict kindest/node to patch updates only

- pkg/telemetry/providers/providers.go
Just a correction on the logging for errors. This allows us to more easily debug via errors in future.
Ref: https://github.com/stacklok/toolhive/issues/1964
> improves error logs for specific service name and version

- .github/workflows/security-scan.yml
The CI was broken due to the `security-scan.yml` workflow missing the `workflow_call` trigger needed to make it reusable. This was causing the `run-on-pr.yml` workflow to fail when trying to call it at line 25.
Error message:
```
.github/workflows/run-on-pr.yml#L25
error parsing called workflow
".github/workflows/run-on-pr.yml"
-> "./.github/workflows/security-scan.yml"
: workflow is not reusable as it is missing a `on.workflow_call` trigger
```
Added the `workflow_call:` trigger to the `security-scan.yml` workflow while preserving all existing triggers:
- `workflow_dispatch`
- `push` (on main branch)
- `pull_request` (on main branch) 
- `schedule` (daily at 2 AM UTC)
This follows the same pattern used by other reusable workflows in the repository like `spellcheck.yml` and `lint.yml`.
The …
> Fix CI: Add workflow_call trigger to security-scan workflow

- docs/remote-mcp-authentication.md
This PR adds comprehensive documentation about ToolHive's remote MCP server authentication implementation, detailing compliance with various RFCs and the MCP authorization specification.
A new documentation file `docs/remote-mcp-authentication.md` that covers:
- RFC 9728 (Protected Resource Metadata)
- RFC 8414 (Authorization Server Metadata) 
- RFC 7591 (Dynamic Client Registration)
- OAuth 2.1 PKCE support
- Complete authentication flow with mermaid diagram
- Discovery priority chain (5 levels)
- Well-known endpoint discovery for issuer mismatch handling
- Dynamic client registration flow
- Security features (HTTPS enforcement, PKCE, token handling)
- CLI flags for remote authentication
- Registry configuration with OAuth settings
- Key component descriptions
- Error handling strategies …
> Add remote MCP authentication documentation

- cmd/thv/app/run_flags.go
- cmd/thv/app/run_flags_test.go
- pkg/api/v1/workload_service.go
- pkg/telemetry/middleware.go
- pkg/telemetry/middleware_test.go
- test/e2e/telemetry_metrics_validation_e2e_test.go
> fix issues with propagating server and transport on telemetry

- .goreleaser.yaml
The `archives.format` and `archives.format_overrides.format` fields were removed in #1969 to clear deprecation warnings, but they should have beenrenamed from `format` to `formats` instead of being removed, per the deprecation notices:
https://goreleaser.com/deprecations/#archivesformat
https://goreleaser.com/deprecations/#archivesformat_overridesformat
This broke the release process because the expected archives were not generated.
> Fix GoReleaser archive formats

- pkg/testkit/sse_server.go
- pkg/testkit/streamable_server.go
- pkg/testkit/testkit.go
- pkg/testkit/testkit_test.go
This change adds a new `testkit` package that should help us write e2e in a simpler way. Its sole purpose is
* adding utilities to quickly spin-up an HTTP test server exposing either a Streamable-HTTP or (legacy) SSE MCP server
* adding utilities to ease the parsing of `text/event-stream` response bodies
The file `pkg/testkit/testkit_test.go` contains a few tests that exemplify how to use the framework, which is barebone at the moment. Ideally, it should allow the developer to add assertions in the test server as well, but for now it only allows configuring the returned JSON payloads.
> Add `pkg/testkit` package

- pkg/authz/middleware_test.go
- pkg/mcp/tool_middleware_test.go
- pkg/testkit/sse_server.go
- pkg/testkit/streamable_server.go
- pkg/testkit/testkit.go
- pkg/testkit/testkit_test.go
This is a follow up of #1189 specifically targeted to SSE streams from different request, i.e. handling of the SSE transport.
This doesn't modify or add any conde under `pkg/authz`, but does add a test pinning the current behavior.
In order to write the test more easily, I added clients to `pkg/testkit` so that when a specific test server is initialized, a pre-configured client exposing `ToolsList()` and `ToolsCall()` routines is returned along.
The returned client masks any transport specific behavior so that developers writing new tests don't have to bother anymore handling SSE streams, goroutines, or channel closure anymore.
Fixes #1188
> Fix authz behavior on `tools/list`

- .github/workflows/claude.yml
Now that the Claude Code action has [reached v1](https://github.com/anthropics/claude-code-action/releases/tag/v1), Anthropic has stopped bumping the `beta` tag.
Updating per the [migration guide](https://github.com/anthropics/claude-code-action/blob/main/docs/migration-guide.md) and the [example](https://github.com/anthropics/claude-code-action/blob/main/examples/claude.yml).
> Update the Claude Code action to v1

- renovate.json
This configuration change gets rid of `chore(deps):` prefix used by Renovate in its PRs. This should make it adhere to our commit message guidelines.
> Change Renovate commit messages

- pkg/auth/oauth/dynamic_registration.go
- pkg/auth/oauth/dynamic_registration_test.go
Some authorization servers return the `scope` field as a space-delimited
string (per RFC 7591), while others return it as a JSON array of strings.
This caused decoding errors when the format didn’t match expectations.
This change introduces a custom `ScopeList` type with a flexible
UnmarshalJSON implementation that correctly handles:
- space-delimited strings (e.g. "openid profile email")
- JSON arrays (e.g. ["openid","profile","email"])
- explicit null values
- empty string values
This ensures consistent behavior and provides a unified []string
representation in Go, regardless of how the server encodes scopes.
> Handle scope field as string or array in DynamicClientRegistrationResponse

- examples/otel/grafana-dashboards/toolhive-cli-mcp-grafana-dashboard-otel-scrape.json
Example Grafana dashboard; modified from the existing K8s version to work with CLI-exported metrics.
Will be used in the CLI "track" of the upcoming tutorial.
> Add sample Grafana dashboard for CLI tutorial

- docs/proposals/token-exchange-middleware.md
> Design proposal: Token exchange to acquire tokens for external auth

- pkg/mcp/server/handler.go
- pkg/mcp/server/handler_test.go
- pkg/mcp/server/list_secrets.go
- pkg/mcp/server/list_secrets_test.go
- pkg/mcp/server/run_server.go
- pkg/mcp/server/server.go
- pkg/mcp/server/set_secret.go
- pkg/mcp/server/set_secret_test.go
This PR implements comprehensive secrets management functionality for the ToolHive MCP server, enabling users to manage secrets and pass them to MCP servers through the MCP interface.
- **`list_secrets`** - Lists all available secrets from the ToolHive secrets store with descriptions
- **`set_secret`** - Sets secrets by reading values from file paths (file-based input only for security)
- Added `secrets` parameter with structured `SecretMapping` objects
- Supports passing secrets to MCP servers when running them
- Converts to runner's expected format (`"secret_name,target=ENV_VAR_NAME"`)
- **Security-focused**: File-based secret input only, no direct value input
- **Comprehensive validation**: File existence, size limits (1MB), content validation
- **Provider integration**: Works with …
> Add secrets management support to ToolHive MCP server
